#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Achievement_Armor_Skin_Set

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct Achievement_Armor_Skin_Set.Achievement_Armor_Skin_Set
// 0x0028 (0x0028 - 0x0000)
struct FAchievement_Armor_Skin_Set final
{
public:
	TSoftClassPtr<class UClass>                   Armor_Skins_30_3453AC17447FD77A291198902E675DCA;   // 0x0000(0x0028)(Edit, BlueprintVisible, DisableEditOnTemplate, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FAchievement_Armor_Skin_Set;

}

