#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ACLPlugin

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "ACLPlugin_structs.hpp"


namespace SDK
{

// Class ACLPlugin.ACLStatsDumpCommandlet
// 0x0000 (0x0080 - 0x0080)
class UACLStatsDumpCommandlet final : public UCommandlet
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ACLStatsDumpCommandlet")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ACLStatsDumpCommandlet")
	}
	static class UACLStatsDumpCommandlet* GetDefaultObj()
	{
		return GetDefaultObjImpl<UACLStatsDumpCommandlet>();
	}
};
DUMPER7_ASSERTS_UACLStatsDumpCommandlet;

// Class ACLPlugin.AnimCompress_ACLBase
// 0x0000 (0x0050 - 0x0050)
class UAnimCompress_ACLBase : public UAnimCompress
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AnimCompress_ACLBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AnimCompress_ACLBase")
	}
	static class UAnimCompress_ACLBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAnimCompress_ACLBase>();
	}
};
DUMPER7_ASSERTS_UAnimCompress_ACLBase;

// Class ACLPlugin.AnimCompress_ACL
// 0x0018 (0x0068 - 0x0050)
class UAnimCompress_ACL final : public UAnimCompress_ACLBase
{
public:
	EACLCompressionLevel                          CompressionLevel;                                  // 0x0050(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_51[0x3];                                       // 0x0051(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         DefaultVirtualVertexDistance;                      // 0x0054(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SafeVirtualVertexDistance;                         // 0x0058(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SafetyFallbackThreshold;                           // 0x005C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ErrorThreshold;                                    // 0x0060(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_64[0x4];                                       // 0x0064(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AnimCompress_ACL")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AnimCompress_ACL")
	}
	static class UAnimCompress_ACL* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAnimCompress_ACL>();
	}
};
DUMPER7_ASSERTS_UAnimCompress_ACL;

// Class ACLPlugin.AnimCompress_ACLCustom
// 0x0028 (0x0078 - 0x0050)
class UAnimCompress_ACLCustom final : public UAnimCompress_ACLBase
{
public:
	float                                         DefaultVirtualVertexDistance;                      // 0x0050(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SafeVirtualVertexDistance;                         // 0x0054(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EACLCompressionLevel                          CompressionLevel;                                  // 0x0058(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EACLRotationFormat                            RotationFormat;                                    // 0x0059(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EACLVectorFormat                              TranslationFormat;                                 // 0x005A(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EACLVectorFormat                              ScaleFormat;                                       // 0x005B(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ErrorThreshold;                                    // 0x005C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ConstantRotationThresholdAngle;                    // 0x0060(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ConstantTranslationThreshold;                      // 0x0064(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ConstantScaleThreshold;                            // 0x0068(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         bClipRangeReduceRotations : 1;                     // 0x006C(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         bClipRangeReduceTranslations : 1;                  // 0x006C(0x0001)(BitIndex: 0x01, PropSize: 0x0001 (Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         bClipRangeReduceScales : 1;                        // 0x006C(0x0001)(BitIndex: 0x02, PropSize: 0x0001 (Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         EnableSegmenting : 1;                              // 0x006C(0x0001)(BitIndex: 0x03, PropSize: 0x0001 (Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         bSegmentRangeReduceRotations : 1;                  // 0x006C(0x0001)(BitIndex: 0x04, PropSize: 0x0001 (Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         bSegmentRangeReduceTranslations : 1;               // 0x006C(0x0001)(BitIndex: 0x05, PropSize: 0x0001 (Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         bSegmentRangeReduceScales : 1;                     // 0x006C(0x0001)(BitIndex: 0x06, PropSize: 0x0001 (Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         Pad_6D[0x3];                                       // 0x006D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	uint16                                        IdealNumKeyFramesPerSegment;                       // 0x0070(0x0002)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint16                                        MaxNumKeyFramesPerSegment;                         // 0x0072(0x0002)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_74[0x4];                                       // 0x0074(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AnimCompress_ACLCustom")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AnimCompress_ACLCustom")
	}
	static class UAnimCompress_ACLCustom* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAnimCompress_ACLCustom>();
	}
};
DUMPER7_ASSERTS_UAnimCompress_ACLCustom;

}

