#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Action_Aura

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GunfireRuntime_structs.hpp"
#include "Action_Buff_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Action_Aura.Action_Aura_C
// 0x0030 (0x02F8 - 0x02C8)
class UAction_Aura_C : public UAction_Buff_C
{
public:
	uint8                                         Pad_2C3[0x5];                                      // 0x02C3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame_Action_Aura_C;                      // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         Radius;                                            // 0x02D0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_2D4[0x4];                                      // 0x02D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 ActionToApply;                                     // 0x02D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          IgnoreSelf;                                        // 0x02E0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          TestCollision;                                     // 0x02E1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          AnimateRadius;                                     // 0x02E2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          RemoveOnEndOverlap;                                // 0x02E3(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	EAffiliation                                  Affiliation;                                       // 0x02E4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2E5[0x3];                                      // 0x02E5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         OverlappingActors;                                 // 0x02E8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance)

public:
	void ExecuteUbergraph_Action_Aura(int32 EntryPoint);
	void OnEndOverlap(class AActor* Actor);
	void OnBeginOverlap(class AActor* Actor);
	void OnTick(float DeltaSeconds);
	void ValidateActor(class AActor* Actor, bool* Out);
	void UpdateOverlaps();
	void GetRadius(float* Radius_0);
	void DoAction(class UActionComponent* ActionComponent);
	void OnActionStop();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Action_Aura_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Action_Aura_C")
	}
	static class UAction_Aura_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAction_Aura_C>();
	}
};
DUMPER7_ASSERTS_UAction_Aura_C;

}

