#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Action_Trinket_BrutalMark_Cooldown

#include "Basic.hpp"

#include "Action_Trinket_BrutalMark_Cooldown_classes.hpp"
#include "Action_Trinket_BrutalMark_Cooldown_parameters.hpp"


namespace SDK
{

// Function Action_Trinket_BrutalMark_Cooldown.Action_Trinket_BrutalMark_Cooldown_C.ExecuteUbergraph_Action_Trinket_BrutalMark_Cooldown
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAction_Trinket_BrutalMark_Cooldown_C::ExecuteUbergraph_Action_Trinket_BrutalMark_Cooldown(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Trinket_BrutalMark_Cooldown_C", "ExecuteUbergraph_Action_Trinket_BrutalMark_Cooldown");

	Params::Action_Trinket_BrutalMark_Cooldown_C_ExecuteUbergraph_Action_Trinket_BrutalMark_Cooldown Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Action_Trinket_BrutalMark_Cooldown.Action_Trinket_BrutalMark_Cooldown_C.OnActionStart
// (Event, Public, BlueprintEvent)

void UAction_Trinket_BrutalMark_Cooldown_C::OnActionStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Trinket_BrutalMark_Cooldown_C", "OnActionStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Action_Trinket_BrutalMark_Cooldown.Action_Trinket_BrutalMark_Cooldown_C.OnActionStop
// (Event, Public, BlueprintEvent)

void UAction_Trinket_BrutalMark_Cooldown_C::OnActionStop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Trinket_BrutalMark_Cooldown_C", "OnActionStop");

	UObject::ProcessEvent(Func, nullptr);
}

}

