#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Action_Buff_Movement_RiftWalker

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Action_Buff_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Action_Buff_Movement_RiftWalker.Action_Buff_Movement_RiftWalker_C
// 0x0008 (0x02D0 - 0x02C8)
class UAction_Buff_Movement_RiftWalker_C final : public UAction_Buff_C
{
public:
	uint8                                         Pad_2C3[0x5];                                      // 0x02C3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame_Action_Buff_Movement_RiftWalker_C;  // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_Action_Buff_Movement_RiftWalker(int32 EntryPoint);
	void OnComputeStats();
	void OnActionStart();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Action_Buff_Movement_RiftWalker_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Action_Buff_Movement_RiftWalker_C")
	}
	static class UAction_Buff_Movement_RiftWalker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAction_Buff_Movement_RiftWalker_C>();
	}
};
DUMPER7_ASSERTS_UAction_Buff_Movement_RiftWalker_C;

}

