#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Action_Mod_Banish_Debuff

#include "Basic.hpp"

#include "Action_Mod_Banish_Debuff_classes.hpp"
#include "Action_Mod_Banish_Debuff_parameters.hpp"


namespace SDK
{

// Function Action_Mod_Banish_Debuff.Action_Mod_Banish_Debuff_C.FilterIncomingDamage
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FDamageInfo&               DamageInfo_0                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// struct FDamageInfo*                     DamageInfoOut                                          (Parm, OutParm, ContainsInstancedReference)
// bool*                                   ShouldApplyDamage                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UAction_Mod_Banish_Debuff_C::FilterIncomingDamage(const struct FDamageInfo& DamageInfo_0, struct FDamageInfo* DamageInfoOut, bool* ShouldApplyDamage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Mod_Banish_Debuff_C", "FilterIncomingDamage");

	Params::Action_Mod_Banish_Debuff_C_FilterIncomingDamage Parms{};

	Parms.DamageInfo_0 = std::move(DamageInfo_0);

	UObject::ProcessEvent(Func, &Parms);

	if (DamageInfoOut != nullptr)
		*DamageInfoOut = std::move(Parms.DamageInfoOut);

	if (ShouldApplyDamage != nullptr)
		*ShouldApplyDamage = Parms.ShouldApplyDamage;
}

}

