#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Action_Consumable_HeavyWaterElixir

#include "Basic.hpp"

#include "Action_Consumable_HeavyWaterElixir_classes.hpp"
#include "Action_Consumable_HeavyWaterElixir_parameters.hpp"


namespace SDK
{

// Function Action_Consumable_HeavyWaterElixir.Action_Consumable_HeavyWaterElixir_C.ExecuteUbergraph_Action_Consumable_HeavyWaterElixir
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAction_Consumable_HeavyWaterElixir_C::ExecuteUbergraph_Action_Consumable_HeavyWaterElixir(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Consumable_HeavyWaterElixir_C", "ExecuteUbergraph_Action_Consumable_HeavyWaterElixir");

	Params::Action_Consumable_HeavyWaterElixir_C_ExecuteUbergraph_Action_Consumable_HeavyWaterElixir Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Action_Consumable_HeavyWaterElixir.Action_Consumable_HeavyWaterElixir_C.OnActionStart
// (Event, Public, BlueprintEvent)

void UAction_Consumable_HeavyWaterElixir_C::OnActionStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Consumable_HeavyWaterElixir_C", "OnActionStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Action_Consumable_HeavyWaterElixir.Action_Consumable_HeavyWaterElixir_C.OnComputeStats
// (Event, Public, BlueprintEvent)

void UAction_Consumable_HeavyWaterElixir_C::OnComputeStats()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Consumable_HeavyWaterElixir_C", "OnComputeStats");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Action_Consumable_HeavyWaterElixir.Action_Consumable_HeavyWaterElixir_C.OnReapplyBuff
// (Public, BlueprintCallable, BlueprintEvent)

void UAction_Consumable_HeavyWaterElixir_C::OnReapplyBuff()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Consumable_HeavyWaterElixir_C", "OnReapplyBuff");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Action_Consumable_HeavyWaterElixir.Action_Consumable_HeavyWaterElixir_C.PlayFX
// (BlueprintCallable, BlueprintEvent)

void UAction_Consumable_HeavyWaterElixir_C::PlayFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Consumable_HeavyWaterElixir_C", "PlayFX");

	UObject::ProcessEvent(Func, nullptr);
}

}

