#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Action_Mod_Blizzard

#include "Basic.hpp"

#include "Action_Mod_Blizzard_classes.hpp"
#include "Action_Mod_Blizzard_parameters.hpp"


namespace SDK
{

// Function Action_Mod_Blizzard.Action_Mod_Blizzard_C.ExecuteUbergraph_Action_Mod_Blizzard
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAction_Mod_Blizzard_C::ExecuteUbergraph_Action_Mod_Blizzard(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Mod_Blizzard_C", "ExecuteUbergraph_Action_Mod_Blizzard");

	Params::Action_Mod_Blizzard_C_ExecuteUbergraph_Action_Mod_Blizzard Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Action_Mod_Blizzard.Action_Mod_Blizzard_C.OnDurationExpired
// (BlueprintCallable, BlueprintEvent)

void UAction_Mod_Blizzard_C::OnDurationExpired()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Mod_Blizzard_C", "OnDurationExpired");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Action_Mod_Blizzard.Action_Mod_Blizzard_C.OnActionStart
// (Event, Public, BlueprintEvent)

void UAction_Mod_Blizzard_C::OnActionStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Mod_Blizzard_C", "OnActionStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Action_Mod_Blizzard.Action_Mod_Blizzard_C.GetDamageCause
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class AActor**                          Out                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAction_Mod_Blizzard_C::GetDamageCause(class AActor** Out)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Mod_Blizzard_C", "GetDamageCause");

	Params::Action_Mod_Blizzard_C_GetDamageCause Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Out != nullptr)
		*Out = Parms.Out;
}


// Function Action_Mod_Blizzard.Action_Mod_Blizzard_C.GetWeapon
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class AActor**                          Out                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAction_Mod_Blizzard_C::GetWeapon(class AActor** Out)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Mod_Blizzard_C", "GetWeapon");

	Params::Action_Mod_Blizzard_C_GetWeapon Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Out != nullptr)
		*Out = Parms.Out;
}

}

