#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Action_Fire_Projectile

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GunfireRuntime_structs.hpp"
#include "GunfireRuntime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Action_Fire_Projectile.Action_Fire_Projectile_C
// 0x0038 (0x0260 - 0x0228)
class UAction_Fire_Projectile_C : public UActionBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0228(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         Speed;                                             // 0x0230(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class FName                                   SourceSocket;                                      // 0x0234(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_23C[0x4];                                      // 0x023C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 ProjectileBP;                                      // 0x0240(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          bOrientTowardsTarget;                              // 0x0248(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_249[0x3];                                      // 0x0249(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         AutoArcHeight;                                     // 0x024C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	float                                         GravityScale;                                      // 0x0250(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	float                                         TargetLead;                                        // 0x0254(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          UseSpeedArc;                                       // 0x0258(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	uint8                                         Pad_259[0x3];                                      // 0x0259(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Spread;                                            // 0x025C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Action_Fire_Projectile(int32 EntryPoint);
	void OnActionStart();
	void FireTheProjectile();
	void GetAutoArc(EAutoArcType* Out);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Action_Fire_Projectile_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Action_Fire_Projectile_C")
	}
	static class UAction_Fire_Projectile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAction_Fire_Projectile_C>();
	}
};
DUMPER7_ASSERTS_UAction_Fire_Projectile_C;

}

