#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Action_Character_Wasteland_Sentinel_Damage

#include "Basic.hpp"

#include "Action_Character_Root_Screamer_Damage_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Action_Character_Wasteland_Sentinel_Damage.Action_Character_Wasteland_Sentinel_Damage_C
// 0x0000 (0x0258 - 0x0258)
class UAction_Character_Wasteland_Sentinel_Damage_C final : public UAction_Character_Root_Screamer_Damage_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Action_Character_Wasteland_Sentinel_Damage_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Action_Character_Wasteland_Sentinel_Damage_C")
	}
	static class UAction_Character_Wasteland_Sentinel_Damage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAction_Character_Wasteland_Sentinel_Damage_C>();
	}
};
DUMPER7_ASSERTS_UAction_Character_Wasteland_Sentinel_Damage_C;

}

