#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AIPOIType_Standing

#include "Basic.hpp"

#include "GunfireRuntime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AIPOIType_Standing.AIPOIType_Standing_C
// 0x0000 (0x0038 - 0x0038)
class UAIPOIType_Standing_C final : public UAIPOIType
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AIPOIType_Standing_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AIPOIType_Standing_C")
	}
	static class UAIPOIType_Standing_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAIPOIType_Standing_C>();
	}
};
DUMPER7_ASSERTS_UAIPOIType_Standing_C;

}

