#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: APOI_Shiver

#include "Basic.hpp"

#include "GunfireRuntime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass APOI_Shiver.APOI_Shiver_C
// 0x0018 (0x0388 - 0x0370)
class AAPOI_Shiver_C final : public AAIPointOfInterest
{
public:
	class UStaticMeshComponent*                   APOI_Shiver_PreviewMesh;                           // 0x0370(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UArrowComponent*                        Arrow;                                             // 0x0378(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0380(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("APOI_Shiver_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"APOI_Shiver_C")
	}
	static class AAPOI_Shiver_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAPOI_Shiver_C>();
	}
};
DUMPER7_ASSERTS_AAPOI_Shiver_C;

}

