#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ArmorSkill_Juggernaut_Action_DisplayStacks

#include "Basic.hpp"

#include "ArmorSkill_Juggernaut_Action_DisplayStacks_classes.hpp"
#include "ArmorSkill_Juggernaut_Action_DisplayStacks_parameters.hpp"


namespace SDK
{

// Function ArmorSkill_Juggernaut_Action_DisplayStacks.ArmorSkill_Juggernaut_Action_DisplayStacks_C.ExecuteUbergraph_ArmorSkill_Juggernaut_Action_DisplayStacks
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UArmorSkill_Juggernaut_Action_DisplayStacks_C::ExecuteUbergraph_ArmorSkill_Juggernaut_Action_DisplayStacks(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ArmorSkill_Juggernaut_Action_DisplayStacks_C", "ExecuteUbergraph_ArmorSkill_Juggernaut_Action_DisplayStacks");

	Params::ArmorSkill_Juggernaut_Action_DisplayStacks_C_ExecuteUbergraph_ArmorSkill_Juggernaut_Action_DisplayStacks Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ArmorSkill_Juggernaut_Action_DisplayStacks.ArmorSkill_Juggernaut_Action_DisplayStacks_C.OnActionStart
// (Event, Public, BlueprintEvent)

void UArmorSkill_Juggernaut_Action_DisplayStacks_C::OnActionStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ArmorSkill_Juggernaut_Action_DisplayStacks_C", "OnActionStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ArmorSkill_Juggernaut_Action_DisplayStacks.ArmorSkill_Juggernaut_Action_DisplayStacks_C.UpdateStackCount
// (BlueprintCallable, BlueprintEvent)

void UArmorSkill_Juggernaut_Action_DisplayStacks_C::UpdateStackCount()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ArmorSkill_Juggernaut_Action_DisplayStacks_C", "UpdateStackCount");

	UObject::ProcessEvent(Func, nullptr);
}

}

