#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BreakableActor_2States

#include "Basic.hpp"

#include "BP_BreakableActor_2States_classes.hpp"
#include "BP_BreakableActor_2States_parameters.hpp"


namespace SDK
{

// Function BP_BreakableActor_2States.BP_BreakableActor_2States_C.EnableCollisionOn2ndState
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_BreakableActor_2States_C::EnableCollisionOn2ndState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BreakableActor_2States_C", "EnableCollisionOn2ndState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BreakableActor_2States.BP_BreakableActor_2States_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_BreakableActor_2States_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BreakableActor_2States_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BreakableActor_2States.BP_BreakableActor_2States_C.BndEvt__Breakable_K2Node_ComponentBoundEvent_1_BreakableEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UBreakableComponent*              Breakable_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BreakableActor_2States_C::BndEvt__Breakable_K2Node_ComponentBoundEvent_1_BreakableEvent__DelegateSignature(class UBreakableComponent* Breakable_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BreakableActor_2States_C", "BndEvt__Breakable_K2Node_ComponentBoundEvent_1_BreakableEvent__DelegateSignature");

	Params::BP_BreakableActor_2States_C_BndEvt__Breakable_K2Node_ComponentBoundEvent_1_BreakableEvent__DelegateSignature Parms{};

	Parms.Breakable_0 = Breakable_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BreakableActor_2States.BP_BreakableActor_2States_C.ExecuteUbergraph_BP_BreakableActor_2States
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BreakableActor_2States_C::ExecuteUbergraph_BP_BreakableActor_2States(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BreakableActor_2States_C", "ExecuteUbergraph_BP_BreakableActor_2States");

	Params::BP_BreakableActor_2States_C_ExecuteUbergraph_BP_BreakableActor_2States Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

