#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Interactive_Hearth_HoundMaster

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_Wasteland_Campfire_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Interactive_Hearth_HoundMaster.BP_Interactive_Hearth_HoundMaster_C
// 0x0028 (0x0398 - 0x0370)
class ABP_Interactive_Hearth_HoundMaster_C final : public ABP_Wasteland_Campfire_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Interactive_Hearth_HoundMaster_C; // 0x0370(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNamedActorComponent*                   NamedActor;                                        // 0x0378(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPersistenceComponent*                  Persistence;                                       // 0x0380(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStateMachineComponent*                 StateMachine;                                      // 0x0388(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class ARemnantCharacter*                      Player;                                            // 0x0390(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveBeginPlay();
	void BndEvt__StateMachine_K2Node_ComponentBoundEvent_1_InteractiveDelegate__DelegateSignature(const class FName& StateName, class AActor* Other);
	void ExecuteUbergraph_BP_Interactive_Hearth_HoundMaster(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Interactive_Hearth_HoundMaster_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Interactive_Hearth_HoundMaster_C")
	}
	static class ABP_Interactive_Hearth_HoundMaster_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Interactive_Hearth_HoundMaster_C>();
	}
};
DUMPER7_ASSERTS_ABP_Interactive_Hearth_HoundMaster_C;

}

