#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Light_A

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Light_A.BP_Light_A_C.ExecuteUbergraph_BP_Light_A
// 0x0008 (0x0008 - 0x0000)
struct BP_Light_A_C_ExecuteUbergraph_BP_Light_A final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_RandomFloatInRange_ReturnValue;           // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Light_A_C_ExecuteUbergraph_BP_Light_A;

// Function BP_Light_A.BP_Light_A_C.UserConstructionScript
// 0x0008 (0x0008 - 0x0000)
struct BP_Light_A_C_UserConstructionScript final
{
public:
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue; // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Light_A_C_UserConstructionScript;

}

