#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PointLight

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_PointLight.BP_PointLight_C.ExecuteUbergraph_BP_PointLight
// 0x0004 (0x0004 - 0x0000)
struct BP_PointLight_C_ExecuteUbergraph_BP_PointLight final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_PointLight_C_ExecuteUbergraph_BP_PointLight;

// Function BP_PointLight.BP_PointLight_C.UserConstructionScript
// 0x0001 (0x0001 - 0x0000)
struct BP_PointLight_C_UserConstructionScript final
{
public:
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_PointLight_C_UserConstructionScript;

}

