#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Root_Base

#include "Basic.hpp"

#include "BP_Root_Base_classes.hpp"
#include "BP_Root_Base_parameters.hpp"


namespace SDK
{

// Function BP_Root_Base.BP_Root_Base_C.ExecuteUbergraph_BP_Root_Base
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Root_Base_C::ExecuteUbergraph_BP_Root_Base(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Root_Base_C", "ExecuteUbergraph_BP_Root_Base");

	Params::BP_Root_Base_C_ExecuteUbergraph_BP_Root_Base Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Root_Base.BP_Root_Base_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Root_Base_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Root_Base_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Root_Base.BP_Root_Base_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Root_Base_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Root_Base_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Root_Base.BP_Root_Base_C.GetNearestTime
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Root_Base_C::GetNearestTime()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Root_Base_C", "GetNearestTime");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Root_Base.BP_Root_Base_C.CreateSplinePointMeshes
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Root_Base_C::CreateSplinePointMeshes(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Root_Base_C", "CreateSplinePointMeshes");

	Params::BP_Root_Base_C_CreateSplinePointMeshes Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Root_Base.BP_Root_Base_C.CreateStartCap
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Root_Base_C::CreateStartCap()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Root_Base_C", "CreateStartCap");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Root_Base.BP_Root_Base_C.CheckForSplinePointSnap
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Local_Location                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   Local_Tangent                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   Local_Location_2                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   Local_Tangent_2                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector*                         Start_Pos                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector*                         Start_Tangent                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector*                         End_Pos                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector*                         End_Tangent                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Root_Base_C::CheckForSplinePointSnap(const struct FVector& Local_Location, const struct FVector& Local_Tangent, const struct FVector& Local_Location_2, const struct FVector& Local_Tangent_2, struct FVector* Start_Pos, struct FVector* Start_Tangent, struct FVector* End_Pos, struct FVector* End_Tangent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Root_Base_C", "CheckForSplinePointSnap");

	Params::BP_Root_Base_C_CheckForSplinePointSnap Parms{};

	Parms.Local_Location = std::move(Local_Location);
	Parms.Local_Tangent = std::move(Local_Tangent);
	Parms.Local_Location_2 = std::move(Local_Location_2);
	Parms.Local_Tangent_2 = std::move(Local_Tangent_2);

	UObject::ProcessEvent(Func, &Parms);

	if (Start_Pos != nullptr)
		*Start_Pos = std::move(Parms.Start_Pos);

	if (Start_Tangent != nullptr)
		*Start_Tangent = std::move(Parms.Start_Tangent);

	if (End_Pos != nullptr)
		*End_Pos = std::move(Parms.End_Pos);

	if (End_Tangent != nullptr)
		*End_Tangent = std::move(Parms.End_Tangent);
}


// Function BP_Root_Base.BP_Root_Base_C.Snap Spline Point To Grid
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Root_Base_C::Snap_Spline_Point_To_Grid(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Root_Base_C", "Snap Spline Point To Grid");

	Params::BP_Root_Base_C_Snap_Spline_Point_To_Grid Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

