#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Camera_GoodBoy

#include "Basic.hpp"

#include "GunfireRuntime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Camera_GoodBoy.Camera_GoodBoy_C
// 0x0000 (0x0288 - 0x0288)
class UCamera_GoodBoy_C final : public UThirdPersonCameraState
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Camera_GoodBoy_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Camera_GoodBoy_C")
	}
	static class UCamera_GoodBoy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCamera_GoodBoy_C>();
	}
};
DUMPER7_ASSERTS_UCamera_GoodBoy_C;

}

