#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Camera_Wounded

#include "Basic.hpp"

#include "GunfireRuntime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Camera_Wounded.Camera_Wounded_C
// 0x0000 (0x0288 - 0x0288)
class UCamera_Wounded_C final : public UThirdPersonCameraState
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Camera_Wounded_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Camera_Wounded_C")
	}
	static class UCamera_Wounded_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCamera_Wounded_C>();
	}
};
DUMPER7_ASSERTS_UCamera_Wounded_C;

}

