#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Character_RiftWalker_Clone_Base

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GunfireRuntime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Character_RiftWalker_Clone_Base.Character_RiftWalker_Clone_Base_C
// 0x00A0 (0x0B90 - 0x0AF0)
class ACharacter_RiftWalker_Clone_Base_C : public AAICharacter
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0AF0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UAudioComponent*                        RiftWalker_Clone_Loop_SC;                          // 0x0AF8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        Rattleweed_Active_Loop_01_SC;                      // 0x0B00(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               VFX_Ambient_Arms;                                  // 0x0B08(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               VFX_Ambient_Head;                                  // 0x0B10(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               VFX_Ambient_Legs;                                  // 0x0B18(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Visual_Head;                                       // 0x0B20(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Visual_Legs;                                       // 0x0B28(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 MeshOverlay;                                       // 0x0B30(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDissolveComponent*                     Dissolve;                                          // 0x0B38(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStateMachineComponent*                 StateMachine;                                      // 0x0B40(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UTargetableComponent*                   Targetable;                                        // 0x0B48(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         CloneHealthMax;                                    // 0x0B50(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	float                                         AggroDistance;                                     // 0x0B54(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         InitialThreat;                                     // 0x0B58(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CloneDuration;                                     // 0x0B5C(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          IsDissolving;                                      // 0x0B60(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B61[0x3];                                      // 0x0B61(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         SpawnTime;                                         // 0x0B64(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         IncrementalThreat;                                 // 0x0B68(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Damage;                                            // 0x0B6C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 NewVar_0;                                          // 0x0B70(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 WeaponCause;                                       // 0x0B78(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class AActor*                                 SpawnedPostProcessActor;                           // 0x0B80(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               SpawnedPartilceSystem;                             // 0x0B88(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Character_RiftWalker_Clone_Base(int32 EntryPoint);
	void ReceiveBeginPlay();
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void NotifyHitTarget(const struct FDamageInfo& DamageInfo);
	void CustomEvent_0(uint8 Reason, class ACharacterGunfire* Character, class AActor* Cause);
	void MC_Explosion();
	void OnSetState();
	void OnAOE();
	void OnPostComputeStats();
	void OnOwnerComputeStats();
	void DestroyMinion();
	void OnTimer();
	void MultiDissolveEvent();
	void FinishSpawning();
	void UserConstructionScript();
	void InitializeNearbyThreat();
	void AddNearbyThreat();
	void CheckSoulEmberTag(float* DamageScalar);
	void ModifyDamage(struct FDamageInfo& Info, bool* Rtn);
	void SpawnPostProcess();
	void StopPostProcess();
	void GetPunisherDamageMod(class AActor* Target_0, float* PunisherMod);
	void GetArmorScalars(const struct FDamageInfo& DamInfo, float* MinionDamageScalar);
	void GetBrutalMarkDamageMod(const struct FDamageInfo& DamageInfo, float* DamageMod);
	void GetExplosionDamageMod(float* Mod);
	void IsValidMinion(bool* Out);
	void GetSpawnTime(float* Time);
	void HasSoulEmberTrinket(bool* Out);
	void MinionHasDamageTag(bool* ExtraDamage, float* DamageScalar);
	void GetCauseDamageScalar(float* Scalar);
	void GetMinionOwner(class AActor** Owner_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Character_RiftWalker_Clone_Base_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Character_RiftWalker_Clone_Base_C")
	}
	static class ACharacter_RiftWalker_Clone_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACharacter_RiftWalker_Clone_Base_C>();
	}
};
DUMPER7_ASSERTS_ACharacter_RiftWalker_Clone_Base_C;

}

