#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Character_Rattleweed

#include "Basic.hpp"

#include "Character_Rattleweed_classes.hpp"
#include "Character_Rattleweed_parameters.hpp"


namespace SDK
{

// Function Character_Rattleweed.Character_Rattleweed_C.ExecuteUbergraph_Character_Rattleweed
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACharacter_Rattleweed_C::ExecuteUbergraph_Character_Rattleweed(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Character_Rattleweed_C", "ExecuteUbergraph_Character_Rattleweed");

	Params::Character_Rattleweed_C_ExecuteUbergraph_Character_Rattleweed Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Character_Rattleweed.Character_Rattleweed_C.MC_Explosion
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ACharacter_Rattleweed_C::MC_Explosion()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Character_Rattleweed_C", "MC_Explosion");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Character_Rattleweed.Character_Rattleweed_C.NotifyHitTarget
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FDamageInfo&               DamageInfo                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void ACharacter_Rattleweed_C::NotifyHitTarget(const struct FDamageInfo& DamageInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Character_Rattleweed_C", "NotifyHitTarget");

	Params::Character_Rattleweed_C_NotifyHitTarget Parms{};

	Parms.DamageInfo = std::move(DamageInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Character_Rattleweed.Character_Rattleweed_C.OnOwnerComputeStats
// (BlueprintCallable, BlueprintEvent)

void ACharacter_Rattleweed_C::OnOwnerComputeStats()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Character_Rattleweed_C", "OnOwnerComputeStats");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Character_Rattleweed.Character_Rattleweed_C.DestroyMinion
// (Public, BlueprintCallable, BlueprintEvent)

void ACharacter_Rattleweed_C::DestroyMinion()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Character_Rattleweed_C", "DestroyMinion");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Character_Rattleweed.Character_Rattleweed_C.MultiDissolveEvent
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ACharacter_Rattleweed_C::MultiDissolveEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Character_Rattleweed_C", "MultiDissolveEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Character_Rattleweed.Character_Rattleweed_C.FinishSpawning
// (BlueprintCallable, BlueprintEvent)

void ACharacter_Rattleweed_C::FinishSpawning()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Character_Rattleweed_C", "FinishSpawning");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Character_Rattleweed.Character_Rattleweed_C.OnComputeStats
// (Event, Protected, BlueprintEvent)

void ACharacter_Rattleweed_C::OnComputeStats()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Character_Rattleweed_C", "OnComputeStats");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Character_Rattleweed.Character_Rattleweed_C.OnDead_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   Reason                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ACharacterGunfire*                Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Cause                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACharacter_Rattleweed_C::OnDead_Event_0(uint8 Reason, class ACharacterGunfire* Character, class AActor* Cause)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Character_Rattleweed_C", "OnDead_Event_0");

	Params::Character_Rattleweed_C_OnDead_Event_0 Parms{};

	Parms.Reason = Reason;
	Parms.Character = Character;
	Parms.Cause = Cause;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Character_Rattleweed.Character_Rattleweed_C.OnTimer
// (BlueprintCallable, BlueprintEvent)

void ACharacter_Rattleweed_C::OnTimer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Character_Rattleweed_C", "OnTimer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Character_Rattleweed.Character_Rattleweed_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ACharacter_Rattleweed_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Character_Rattleweed_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Character_Rattleweed.Character_Rattleweed_C.MC_BuildUp
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ACharacter_Rattleweed_C::MC_BuildUp()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Character_Rattleweed_C", "MC_BuildUp");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Character_Rattleweed.Character_Rattleweed_C.InitializeNearbyThreat
// (Public, BlueprintCallable, BlueprintEvent)

void ACharacter_Rattleweed_C::InitializeNearbyThreat()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Character_Rattleweed_C", "InitializeNearbyThreat");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Character_Rattleweed.Character_Rattleweed_C.AddNearbyThreat
// (Public, BlueprintCallable, BlueprintEvent)

void ACharacter_Rattleweed_C::AddNearbyThreat()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Character_Rattleweed_C", "AddNearbyThreat");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Character_Rattleweed.Character_Rattleweed_C.ModifyDamage
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FDamageInfo&                     Info                                                   (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// bool*                                   Rtn                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ACharacter_Rattleweed_C::ModifyDamage(struct FDamageInfo& Info, bool* Rtn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Character_Rattleweed_C", "ModifyDamage");

	Params::Character_Rattleweed_C_ModifyDamage Parms{};

	Parms.Info = std::move(Info);

	UObject::ProcessEvent(Func, &Parms);

	Info = std::move(Parms.Info);

	if (Rtn != nullptr)
		*Rtn = Parms.Rtn;
}


// Function Character_Rattleweed.Character_Rattleweed_C.GetPunisherDamageMod
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class AActor*                           Target_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float*                                  PunisherMod                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACharacter_Rattleweed_C::GetPunisherDamageMod(class AActor* Target_0, float* PunisherMod)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Character_Rattleweed_C", "GetPunisherDamageMod");

	Params::Character_Rattleweed_C_GetPunisherDamageMod Parms{};

	Parms.Target_0 = Target_0;

	UObject::ProcessEvent(Func, &Parms);

	if (PunisherMod != nullptr)
		*PunisherMod = Parms.PunisherMod;
}


// Function Character_Rattleweed.Character_Rattleweed_C.IsValidMinion
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Out                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ACharacter_Rattleweed_C::IsValidMinion(bool* Out)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Character_Rattleweed_C", "IsValidMinion");

	Params::Character_Rattleweed_C_IsValidMinion Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Out != nullptr)
		*Out = Parms.Out;
}


// Function Character_Rattleweed.Character_Rattleweed_C.GetSpawnTime
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float*                                  Time                                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACharacter_Rattleweed_C::GetSpawnTime(float* Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Character_Rattleweed_C", "GetSpawnTime");

	Params::Character_Rattleweed_C_GetSpawnTime Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Time != nullptr)
		*Time = Parms.Time;
}


// Function Character_Rattleweed.Character_Rattleweed_C.HasSoulEmberTrinket
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Out                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ACharacter_Rattleweed_C::HasSoulEmberTrinket(bool* Out)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Character_Rattleweed_C", "HasSoulEmberTrinket");

	Params::Character_Rattleweed_C_HasSoulEmberTrinket Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Out != nullptr)
		*Out = Parms.Out;
}


// Function Character_Rattleweed.Character_Rattleweed_C.MinionHasDamageTag
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   ExtraDamage                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
// float*                                  DamageScalar                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACharacter_Rattleweed_C::MinionHasDamageTag(bool* ExtraDamage, float* DamageScalar)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Character_Rattleweed_C", "MinionHasDamageTag");

	Params::Character_Rattleweed_C_MinionHasDamageTag Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ExtraDamage != nullptr)
		*ExtraDamage = Parms.ExtraDamage;

	if (DamageScalar != nullptr)
		*DamageScalar = Parms.DamageScalar;
}


// Function Character_Rattleweed.Character_Rattleweed_C.GetCauseDamageScalar
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float*                                  Scalar                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACharacter_Rattleweed_C::GetCauseDamageScalar(float* Scalar)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Character_Rattleweed_C", "GetCauseDamageScalar");

	Params::Character_Rattleweed_C_GetCauseDamageScalar Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Scalar != nullptr)
		*Scalar = Parms.Scalar;
}


// Function Character_Rattleweed.Character_Rattleweed_C.GetMinionOwner
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor**                          Owner_0                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACharacter_Rattleweed_C::GetMinionOwner(class AActor** Owner_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Character_Rattleweed_C", "GetMinionOwner");

	Params::Character_Rattleweed_C_GetMinionOwner Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Owner_0 != nullptr)
		*Owner_0 = Parms.Owner_0;
}

}

