#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Character_Swamp_SlimeHulk_Projectile_Hit

#include "Basic.hpp"

#include "Character_Swamp_SlimeHulk_Projectile_Hit_classes.hpp"
#include "Character_Swamp_SlimeHulk_Projectile_Hit_parameters.hpp"


namespace SDK
{

// Function Character_Swamp_SlimeHulk_Projectile_Hit.Character_Swamp_SlimeHulk_Projectile_Hit_C.OnActionStart
// (Event, Public, BlueprintEvent)

void UCharacter_Swamp_SlimeHulk_Projectile_Hit_C::OnActionStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Character_Swamp_SlimeHulk_Projectile_Hit_C", "OnActionStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Character_Swamp_SlimeHulk_Projectile_Hit.Character_Swamp_SlimeHulk_Projectile_Hit_C.ExecuteUbergraph_Character_Swamp_SlimeHulk_Projectile_Hit
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCharacter_Swamp_SlimeHulk_Projectile_Hit_C::ExecuteUbergraph_Character_Swamp_SlimeHulk_Projectile_Hit(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Character_Swamp_SlimeHulk_Projectile_Hit_C", "ExecuteUbergraph_Character_Swamp_SlimeHulk_Projectile_Hit");

	Params::Character_Swamp_SlimeHulk_Projectile_Hit_C_ExecuteUbergraph_Character_Swamp_SlimeHulk_Projectile_Hit Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

