#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Consumable_SurvivorBag

#include "Basic.hpp"

#include "Consumable_SurvivorBag_classes.hpp"
#include "Consumable_SurvivorBag_parameters.hpp"


namespace SDK
{

// Function Consumable_SurvivorBag.Consumable_SurvivorBag_C.ExecuteUbergraph_Consumable_SurvivorBag
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AConsumable_SurvivorBag_C::ExecuteUbergraph_Consumable_SurvivorBag(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Consumable_SurvivorBag_C", "ExecuteUbergraph_Consumable_SurvivorBag");

	Params::Consumable_SurvivorBag_C_ExecuteUbergraph_Consumable_SurvivorBag Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Consumable_SurvivorBag.Consumable_SurvivorBag_C.Use
// (Event, Public, BlueprintEvent)

void AConsumable_SurvivorBag_C::Use()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Consumable_SurvivorBag_C", "Use");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Consumable_SurvivorBag.Consumable_SurvivorBag_C.ModifyInspectInfo
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UItemInstanceData*                InInstanceData                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FInspectInfo&                    Info                                                   (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool*                                   Rtn                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AConsumable_SurvivorBag_C::ModifyInspectInfo(class AActor* Actor, class UItemInstanceData* InInstanceData, struct FInspectInfo& Info, bool* Rtn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Consumable_SurvivorBag_C", "ModifyInspectInfo");

	Params::Consumable_SurvivorBag_C_ModifyInspectInfo Parms{};

	Parms.Actor = Actor;
	Parms.InInstanceData = InInstanceData;
	Parms.Info = std::move(Info);

	UObject::ProcessEvent(Func, &Parms);

	Info = std::move(Parms.Info);

	if (Rtn != nullptr)
		*Rtn = Parms.Rtn;
}


// Function Consumable_SurvivorBag.Consumable_SurvivorBag_C.ValidateUse
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool AConsumable_SurvivorBag_C::ValidateUse(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Consumable_SurvivorBag_C", "ValidateUse");

	Params::Consumable_SurvivorBag_C_ValidateUse Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

