#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Consumable_DragonHeart_Action

#include "Basic.hpp"


namespace SDK::Params
{

// Function Consumable_DragonHeart_Action.Consumable_DragonHeart_Action_C.ExecuteUbergraph_Consumable_DragonHeart_Action
// 0x0014 (0x0014 - 0x0000)
struct Consumable_DragonHeart_Action_C_ExecuteUbergraph_Consumable_DragonHeart_Action final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetStat_ReturnValue;                      // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_ApplyMod_ReturnValue;                     // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Consumable_DragonHeart_Action_C_ExecuteUbergraph_Consumable_DragonHeart_Action;

}

