#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DamageType_Melee_Root_Power_01_HeavyHit

#include "Basic.hpp"

#include "GunfireRuntime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DamageType_Melee_Root_Power_01_HeavyHit.DamageType_Melee_Root_Power_01_HeavyHit_C
// 0x0000 (0x0108 - 0x0108)
class UDamageType_Melee_Root_Power_01_HeavyHit_C final : public UDamageTypeGunfire
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DamageType_Melee_Root_Power_01_HeavyHit_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DamageType_Melee_Root_Power_01_HeavyHit_C")
	}
	static class UDamageType_Melee_Root_Power_01_HeavyHit_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDamageType_Melee_Root_Power_01_HeavyHit_C>();
	}
};
DUMPER7_ASSERTS_UDamageType_Melee_Root_Power_01_HeavyHit_C;

}

