#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Dialog_Inventory_SkinSelect

#include "Basic.hpp"

#include "Dialog_InGameBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Dialog_Inventory_SkinSelect.Dialog_Inventory_SkinSelect_C
// 0x0000 (0x03E0 - 0x03E0)
class ADialog_Inventory_SkinSelect_C final : public ADialog_InGameBase_C
{
public:
	void Init(int32 ItemID);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Dialog_Inventory_SkinSelect_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Dialog_Inventory_SkinSelect_C")
	}
	static class ADialog_Inventory_SkinSelect_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADialog_Inventory_SkinSelect_C>();
	}
};
DUMPER7_ASSERTS_ADialog_Inventory_SkinSelect_C;

}

