#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Dialog_Wounded

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Dialog_InGameBase_classes.hpp"
#include "GunfireRuntime_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Dialog_Wounded.Dialog_Wounded_C
// 0x0008 (0x03E8 - 0x03E0)
class ADialog_Wounded_C final : public ADialog_InGameBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Dialog_Wounded_C;                   // 0x03E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_Dialog_Wounded(int32 EntryPoint);
	void OnEndDialog();
	void OnWoundedState_Event_0(class UWoundedComponent* WoundedComponent, EWoundedState State);
	void OnBeginDialog();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Dialog_Wounded_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Dialog_Wounded_C")
	}
	static class ADialog_Wounded_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADialog_Wounded_C>();
	}
};
DUMPER7_ASSERTS_ADialog_Wounded_C;

}

