#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Dialog_Inventory_SkinSelect

#include "Basic.hpp"

#include "Dialog_Inventory_SkinSelect_classes.hpp"
#include "Dialog_Inventory_SkinSelect_parameters.hpp"


namespace SDK
{

// Function Dialog_Inventory_SkinSelect.Dialog_Inventory_SkinSelect_C.Init
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ItemID                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ADialog_Inventory_SkinSelect_C::Init(int32 ItemID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Dialog_Inventory_SkinSelect_C", "Init");

	Params::Dialog_Inventory_SkinSelect_C_Init Parms{};

	Parms.ItemID = ItemID;

	UObject::ProcessEvent(Func, &Parms);
}

}

