#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ImpactEffect_Weapon_Blade_Metal_Medium

#include "Basic.hpp"

#include "ImpactEffect_Weapon_Melee_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ImpactEffect_Weapon_Blade_Metal_Medium.ImpactEffect_Weapon_Blade_Metal_Medium_C
// 0x0000 (0x0490 - 0x0490)
class AImpactEffect_Weapon_Blade_Metal_Medium_C final : public AImpactEffect_Weapon_Melee_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ImpactEffect_Weapon_Blade_Metal_Medium_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ImpactEffect_Weapon_Blade_Metal_Medium_C")
	}
	static class AImpactEffect_Weapon_Blade_Metal_Medium_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AImpactEffect_Weapon_Blade_Metal_Medium_C>();
	}
};
DUMPER7_ASSERTS_AImpactEffect_Weapon_Blade_Metal_Medium_C;

}

