#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Interactive_Fusebox

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_Inspectable_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Interactive_Fusebox.Interactive_Fusebox_C
// 0x0070 (0x0498 - 0x0428)
class AInteractive_Fusebox_C final : public ABP_Inspectable_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Interactive_Fusebox_C;              // 0x0428(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UArrowComponent*                        Interact_Validator;                                // 0x0430(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               VFX_Fusebox_TurnOn;                                // 0x0438(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        Fusebox_On_Stop_SC;                                // 0x0440(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        Fusebox_On_Loop_SC;                                // 0x0448(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        Fusebox_On_Start_SC;                               // 0x0450(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_PowerUser_C*                        BP_PowerUser;                                      // 0x0458(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Fuse;                                              // 0x0460(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPersistenceComponent*                  Persistence;                                       // 0x0468(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Fusebox;                                           // 0x0470(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          HasFuse;                                           // 0x0478(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, SaveGame, IsPlainOldData, RepNotify, NoDestructor)
	bool                                          On;                                                // 0x0479(0x0001)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor)
	uint8                                         Pad_47A[0x6];                                      // 0x047A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 FuseBP;                                            // 0x0480(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         TriggerObjects;                                    // 0x0488(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate)

public:
	void ExecuteUbergraph_Interactive_Fusebox(int32 EntryPoint);
	void OnInsertFuse();
	void BndEvt__BP_PowerUser_K2Node_ComponentBoundEvent_0_OnEnabled__DelegateSignature(bool Enabled);
	void OnTurnOff();
	void OnTurnOn();
	void DelayedUpdateTriggerObjects(float Delay);
	void UseItem(class APlayerControllerGunfire* PlayerController, TSubclassOf<class AItem> ItemClass);
	void UpdateState();
	void UpdateTriggerObjects();
	void OnRep_HasFuse();
	bool CanUseItem(class APlayerControllerGunfire* PlayerController, TSubclassOf<class AItem> ItemClass);
	void HasFuseInFusebox(bool* Out);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Interactive_Fusebox_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Interactive_Fusebox_C")
	}
	static class AInteractive_Fusebox_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AInteractive_Fusebox_C>();
	}
};
DUMPER7_ASSERTS_AInteractive_Fusebox_C;

}

