#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Interactive_City_SingleDoor

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_Inspectable_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Interactive_City_SingleDoor.Interactive_City_SingleDoor_C
// 0x0060 (0x0488 - 0x0428)
class AInteractive_City_SingleDoor_C final : public ABP_Inspectable_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Interactive_City_SingleDoor_C;      // 0x0428(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USoundSetComponent*                     SoundSet;                                          // 0x0430(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPersistenceComponent*                  Persistence;                                       // 0x0438(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USoftCollisionCapsuleComponent*         PlayerPusher_SoftCollisionCapsule;                 // 0x0440(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNamedActorComponent*                   NamedActor;                                        // 0x0448(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        UI_Node_Deadbolt;                                  // 0x0450(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          DoorCollision;                                     // 0x0458(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Mesh;                                              // 0x0460(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 Key;                                               // 0x0468(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Locked;                                            // 0x0470(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, SaveGame, IsPlainOldData, NoDestructor)
	uint8                                         Pad_471[0x7];                                      // 0x0471(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CachedOther;                                       // 0x0478(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          RemoveKeyFromInventory;                            // 0x0480(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          IsInside;                                          // 0x0481(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_Interactive_City_SingleDoor(int32 EntryPoint);
	void HandleEndInspect();
	void OnOpenedDoor();
	void OnOpenDoor();
	void BndEvt__StateMachine_K2Node_ComponentBoundEvent_2_InteractiveDelegate__DelegateSignature(const class FName& StateName, class AActor* Other);
	void OnBeginInspect();
	void BndEvt__Inspectable_K2Node_ComponentBoundEvent_0_InspectableEvent__DelegateSignature(class UInspectableComponent* Component);
	void UseItem(class APlayerControllerGunfire* PlayerController, TSubclassOf<class AItem> ItemClass);
	void ReceiveBeginPlay();
	void OnRep_Locked();
	bool CanUseItem(class APlayerControllerGunfire* PlayerController, TSubclassOf<class AItem> ItemClass);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Interactive_City_SingleDoor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Interactive_City_SingleDoor_C")
	}
	static class AInteractive_City_SingleDoor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AInteractive_City_SingleDoor_C>();
	}
};
DUMPER7_ASSERTS_AInteractive_City_SingleDoor_C;

}

