#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Interactive_DragonCrystal_SpawnPoint

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GunfireRuntime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Interactive_DragonCrystal_SpawnPoint.Interactive_DragonCrystal_SpawnPoint_C
// 0x0028 (0x03A8 - 0x0380)
class AInteractive_DragonCrystal_SpawnPoint_C : public ASpawnPoint
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0380(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCapsuleComponent*                      PawnDetect;                                        // 0x0388(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UArrowComponent*                        Arrow;                                             // 0x0390(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Cylinder;                                          // 0x0398(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          IsActuallyDragonCrystal;                           // 0x03A0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void UpdateEnabled();
	void BndEvt__PawnDetect_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void BndEvt__PawnDetect_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex);
	void OnPreSpawn(class AActor* Actor);
	void ExecuteUbergraph_Interactive_DragonCrystal_SpawnPoint(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Interactive_DragonCrystal_SpawnPoint_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Interactive_DragonCrystal_SpawnPoint_C")
	}
	static class AInteractive_DragonCrystal_SpawnPoint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AInteractive_DragonCrystal_SpawnPoint_C>();
	}
};
DUMPER7_ASSERTS_AInteractive_DragonCrystal_SpawnPoint_C;

}

