#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Interactive_Fusebox

#include "Basic.hpp"

#include "Interactive_Fusebox_classes.hpp"
#include "Interactive_Fusebox_parameters.hpp"


namespace SDK
{

// Function Interactive_Fusebox.Interactive_Fusebox_C.ExecuteUbergraph_Interactive_Fusebox
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AInteractive_Fusebox_C::ExecuteUbergraph_Interactive_Fusebox(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Interactive_Fusebox_C", "ExecuteUbergraph_Interactive_Fusebox");

	Params::Interactive_Fusebox_C_ExecuteUbergraph_Interactive_Fusebox Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Interactive_Fusebox.Interactive_Fusebox_C.OnInsertFuse
// (BlueprintCallable, BlueprintEvent)

void AInteractive_Fusebox_C::OnInsertFuse()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Interactive_Fusebox_C", "OnInsertFuse");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Interactive_Fusebox.Interactive_Fusebox_C.BndEvt__BP_PowerUser_K2Node_ComponentBoundEvent_0_OnEnabled__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    Enabled                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AInteractive_Fusebox_C::BndEvt__BP_PowerUser_K2Node_ComponentBoundEvent_0_OnEnabled__DelegateSignature(bool Enabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Interactive_Fusebox_C", "BndEvt__BP_PowerUser_K2Node_ComponentBoundEvent_0_OnEnabled__DelegateSignature");

	Params::Interactive_Fusebox_C_BndEvt__BP_PowerUser_K2Node_ComponentBoundEvent_0_OnEnabled__DelegateSignature Parms{};

	Parms.Enabled = Enabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Interactive_Fusebox.Interactive_Fusebox_C.OnTurnOff
// (BlueprintCallable, BlueprintEvent)

void AInteractive_Fusebox_C::OnTurnOff()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Interactive_Fusebox_C", "OnTurnOff");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Interactive_Fusebox.Interactive_Fusebox_C.OnTurnOn
// (BlueprintCallable, BlueprintEvent)

void AInteractive_Fusebox_C::OnTurnOn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Interactive_Fusebox_C", "OnTurnOn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Interactive_Fusebox.Interactive_Fusebox_C.DelayedUpdateTriggerObjects
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Delay                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AInteractive_Fusebox_C::DelayedUpdateTriggerObjects(float Delay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Interactive_Fusebox_C", "DelayedUpdateTriggerObjects");

	Params::Interactive_Fusebox_C_DelayedUpdateTriggerObjects Parms{};

	Parms.Delay = Delay;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Interactive_Fusebox.Interactive_Fusebox_C.UseItem
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerControllerGunfire*         PlayerController                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TSubclassOf<class AItem>                ItemClass                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

void AInteractive_Fusebox_C::UseItem(class APlayerControllerGunfire* PlayerController, TSubclassOf<class AItem> ItemClass)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Interactive_Fusebox_C", "UseItem");

	Params::Interactive_Fusebox_C_UseItem Parms{};

	Parms.PlayerController = PlayerController;
	Parms.ItemClass = ItemClass;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Interactive_Fusebox.Interactive_Fusebox_C.UpdateState
// (Public, BlueprintCallable, BlueprintEvent)

void AInteractive_Fusebox_C::UpdateState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Interactive_Fusebox_C", "UpdateState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Interactive_Fusebox.Interactive_Fusebox_C.UpdateTriggerObjects
// (Public, BlueprintCallable, BlueprintEvent)

void AInteractive_Fusebox_C::UpdateTriggerObjects()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Interactive_Fusebox_C", "UpdateTriggerObjects");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Interactive_Fusebox.Interactive_Fusebox_C.OnRep_HasFuse
// (BlueprintCallable, BlueprintEvent)

void AInteractive_Fusebox_C::OnRep_HasFuse()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Interactive_Fusebox_C", "OnRep_HasFuse");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Interactive_Fusebox.Interactive_Fusebox_C.CanUseItem
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerControllerGunfire*         PlayerController                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TSubclassOf<class AItem>                ItemClass                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool AInteractive_Fusebox_C::CanUseItem(class APlayerControllerGunfire* PlayerController, TSubclassOf<class AItem> ItemClass)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Interactive_Fusebox_C", "CanUseItem");

	Params::Interactive_Fusebox_C_CanUseItem Parms{};

	Parms.PlayerController = PlayerController;
	Parms.ItemClass = ItemClass;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Interactive_Fusebox.Interactive_Fusebox_C.HasFuseInFusebox
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Out                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AInteractive_Fusebox_C::HasFuseInFusebox(bool* Out)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Interactive_Fusebox_C", "HasFuseInFusebox");

	Params::Interactive_Fusebox_C_HasFuseInFusebox Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Out != nullptr)
		*Out = Parms.Out;
}


// Function Interactive_Fusebox.Interactive_Fusebox_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AInteractive_Fusebox_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Interactive_Fusebox_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

