#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ItemType_Helmet

#include "Basic.hpp"

#include "GunfireRuntime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ItemType_Helmet.ItemType_Helmet_C
// 0x0000 (0x0080 - 0x0080)
class UItemType_Helmet_C final : public UItemType
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ItemType_Helmet_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ItemType_Helmet_C")
	}
	static class UItemType_Helmet_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UItemType_Helmet_C>();
	}
};
DUMPER7_ASSERTS_UItemType_Helmet_C;

}

