#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Mod_TentacleShot

#include "Basic.hpp"

#include "Mod_TentacleShot_classes.hpp"
#include "Mod_TentacleShot_parameters.hpp"


namespace SDK
{

// Function Mod_TentacleShot.Mod_TentacleShot_C.ExecuteUbergraph_Mod_TentacleShot
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMod_TentacleShot_C::ExecuteUbergraph_Mod_TentacleShot(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mod_TentacleShot_C", "ExecuteUbergraph_Mod_TentacleShot");

	Params::Mod_TentacleShot_C_ExecuteUbergraph_Mod_TentacleShot Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Mod_TentacleShot.Mod_TentacleShot_C.OnPreActivate
// (Event, Public, BlueprintEvent)

void AMod_TentacleShot_C::OnPreActivate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mod_TentacleShot_C", "OnPreActivate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Mod_TentacleShot.Mod_TentacleShot_C.OnFire
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FVector&                   from                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   to                                                     (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   WeaponSpread                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMod_TentacleShot_C::OnFire(const struct FVector& from, const struct FVector& to, float WeaponSpread)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mod_TentacleShot_C", "OnFire");

	Params::Mod_TentacleShot_C_OnFire Parms{};

	Parms.from = std::move(from);
	Parms.to = std::move(to);
	Parms.WeaponSpread = WeaponSpread;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Mod_TentacleShot.Mod_TentacleShot_C.GetHealthMax
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float*                                  Out                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMod_TentacleShot_C::GetHealthMax(float* Out)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mod_TentacleShot_C", "GetHealthMax");

	Params::Mod_TentacleShot_C_GetHealthMax Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Out != nullptr)
		*Out = Parms.Out;
}


// Function Mod_TentacleShot.Mod_TentacleShot_C.ModifyInspectInfo
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UItemInstanceData*                InInstanceData                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FInspectInfo&                    Info                                                   (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool*                                   Rtn                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AMod_TentacleShot_C::ModifyInspectInfo(class AActor* Actor, class UItemInstanceData* InInstanceData, struct FInspectInfo& Info, bool* Rtn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mod_TentacleShot_C", "ModifyInspectInfo");

	Params::Mod_TentacleShot_C_ModifyInspectInfo Parms{};

	Parms.Actor = Actor;
	Parms.InInstanceData = InInstanceData;
	Parms.Info = std::move(Info);

	UObject::ProcessEvent(Func, &Parms);

	Info = std::move(Parms.Info);

	if (Rtn != nullptr)
		*Rtn = Parms.Rtn;
}


// Function Mod_TentacleShot.Mod_TentacleShot_C.ModifyDamage
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FDamageInfo&                     Info                                                   (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// bool*                                   Rtn                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AMod_TentacleShot_C::ModifyDamage(struct FDamageInfo& Info, bool* Rtn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mod_TentacleShot_C", "ModifyDamage");

	Params::Mod_TentacleShot_C_ModifyDamage Parms{};

	Parms.Info = std::move(Info);

	UObject::ProcessEvent(Func, &Parms);

	Info = std::move(Parms.Info);

	if (Rtn != nullptr)
		*Rtn = Parms.Rtn;
}


// Function Mod_TentacleShot.Mod_TentacleShot_C.GetDuration
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float*                                  Out                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMod_TentacleShot_C::GetDuration(float* Out)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mod_TentacleShot_C", "GetDuration");

	Params::Mod_TentacleShot_C_GetDuration Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Out != nullptr)
		*Out = Parms.Out;
}


// Function Mod_TentacleShot.Mod_TentacleShot_C.GetDamage
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float*                                  Out                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMod_TentacleShot_C::GetDamage(float* Out)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mod_TentacleShot_C", "GetDamage");

	Params::Mod_TentacleShot_C_GetDamage Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Out != nullptr)
		*Out = Parms.Out;
}


// Function Mod_TentacleShot.Mod_TentacleShot_C.GetHealthPerHitScalar
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float*                                  Scalar                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMod_TentacleShot_C::GetHealthPerHitScalar(float* Scalar)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mod_TentacleShot_C", "GetHealthPerHitScalar");

	Params::Mod_TentacleShot_C_GetHealthPerHitScalar Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Scalar != nullptr)
		*Scalar = Parms.Scalar;
}


// Function Mod_TentacleShot.Mod_TentacleShot_C.GetTentacleHealthScalar
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float*                                  Out                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMod_TentacleShot_C::GetTentacleHealthScalar(float* Out)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mod_TentacleShot_C", "GetTentacleHealthScalar");

	Params::Mod_TentacleShot_C_GetTentacleHealthScalar Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Out != nullptr)
		*Out = Parms.Out;
}

}

