#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Mod_Beckon

#include "Basic.hpp"

#include "RangedWeapon_Mod_Action_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Mod_Beckon.Mod_Beckon_C
// 0x0008 (0x0718 - 0x0710)
class AMod_Beckon_C final : public ARangedWeapon_Mod_Action_C
{
public:
	float                                         Damage;                                            // 0x070C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Duration;                                          // 0x0710(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         HealthMax;                                         // 0x0714(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ModifyInspectInfo(class AActor* Actor, class UItemInstanceData* InInstanceData, struct FInspectInfo& Info, bool* Rtn);
	float GetSkullDamage();
	float GetDuration();
	void DoAction(class UActionComponent* ActionComponent, int32* ActionID);
	void GetSkullHealthScalar(float* Out);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Mod_Beckon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Mod_Beckon_C")
	}
	static class AMod_Beckon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMod_Beckon_C>();
	}
};
DUMPER7_ASSERTS_AMod_Beckon_C;

}

