#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Mod_ExplosiveShot_Projectile

#include "Basic.hpp"

#include "Mod_ExplosiveShot_Projectile_classes.hpp"
#include "Mod_ExplosiveShot_Projectile_parameters.hpp"


namespace SDK
{

// Function Mod_ExplosiveShot_Projectile.Mod_ExplosiveShot_Projectile_C.ExecuteUbergraph_Mod_ExplosiveShot_Projectile
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMod_ExplosiveShot_Projectile_C::ExecuteUbergraph_Mod_ExplosiveShot_Projectile(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mod_ExplosiveShot_Projectile_C", "ExecuteUbergraph_Mod_ExplosiveShot_Projectile");

	Params::Mod_ExplosiveShot_Projectile_C_ExecuteUbergraph_Mod_ExplosiveShot_Projectile Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Mod_ExplosiveShot_Projectile.Mod_ExplosiveShot_Projectile_C.OnProjectileHit
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FHitResult&                Hit                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void AMod_ExplosiveShot_Projectile_C::OnProjectileHit(const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mod_ExplosiveShot_Projectile_C", "OnProjectileHit");

	Params::Mod_ExplosiveShot_Projectile_C_OnProjectileHit Parms{};

	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}

}

