#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Mod_MendersAura_Aura

#include "Basic.hpp"

#include "Mod_MendersAura_Aura_classes.hpp"
#include "Mod_MendersAura_Aura_parameters.hpp"


namespace SDK
{

// Function Mod_MendersAura_Aura.Mod_MendersAura_Aura_C.ExecuteUbergraph_Mod_MendersAura_Aura
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMod_MendersAura_Aura_C::ExecuteUbergraph_Mod_MendersAura_Aura(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mod_MendersAura_Aura_C", "ExecuteUbergraph_Mod_MendersAura_Aura");

	Params::Mod_MendersAura_Aura_C_ExecuteUbergraph_Mod_MendersAura_Aura Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Mod_MendersAura_Aura.Mod_MendersAura_Aura_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMod_MendersAura_Aura_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mod_MendersAura_Aura_C", "ReceiveTick");

	Params::Mod_MendersAura_Aura_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Mod_MendersAura_Aura.Mod_MendersAura_Aura_C.FadeOut
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   FadeTime                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMod_MendersAura_Aura_C::FadeOut(float FadeTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mod_MendersAura_Aura_C", "FadeOut");

	Params::Mod_MendersAura_Aura_C_FadeOut Parms{};

	Parms.FadeTime = FadeTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Mod_MendersAura_Aura.Mod_MendersAura_Aura_C.StopAction
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACharacterGunfire*                Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMod_MendersAura_Aura_C::StopAction(class ACharacterGunfire* Character)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mod_MendersAura_Aura_C", "StopAction");

	Params::Mod_MendersAura_Aura_C_StopAction Parms{};

	Parms.Character = Character;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Mod_MendersAura_Aura.Mod_MendersAura_Aura_C.DoAction
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACharacterGunfire*                TargetCharacter                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UActionComponent*                 ActionComp                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMod_MendersAura_Aura_C::DoAction(class ACharacterGunfire* TargetCharacter, class UActionComponent* ActionComp)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mod_MendersAura_Aura_C", "DoAction");

	Params::Mod_MendersAura_Aura_C_DoAction Parms{};

	Parms.TargetCharacter = TargetCharacter;
	Parms.ActionComp = ActionComp;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Mod_MendersAura_Aura.Mod_MendersAura_Aura_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AMod_MendersAura_Aura_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mod_MendersAura_Aura_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Mod_MendersAura_Aura.Mod_MendersAura_Aura_C.CanDoAction
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class ACharacterGunfire*                Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Out                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AMod_MendersAura_Aura_C::CanDoAction(class ACharacterGunfire* Character, bool* Out)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mod_MendersAura_Aura_C", "CanDoAction");

	Params::Mod_MendersAura_Aura_C_CanDoAction Parms{};

	Parms.Character = Character;

	UObject::ProcessEvent(Func, &Parms);

	if (Out != nullptr)
		*Out = Parms.Out;
}

}

