#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Mod_MultiTarget_PendingTarget

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct Mod_MultiTarget_PendingTarget.Mod_MultiTarget_PendingTarget
// 0x0018 (0x0018 - 0x0000)
struct FMod_MultiTarget_PendingTarget final
{
public:
	class AActor*                                 Target_7_5158E1D744C1D1492821D29A10661FF9;         // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         Projectiles_6_0EA03AB44B6FABDA9AC03C834E45C02A;    // 0x0008(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate)
};
DUMPER7_ASSERTS_FMod_MultiTarget_PendingTarget;

}

