#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Mod_ExplosiveShot_Projectile

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GunfireRuntime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Mod_ExplosiveShot_Projectile.Mod_ExplosiveShot_Projectile_C
// 0x0020 (0x04A8 - 0x0488)
class AMod_ExplosiveShot_Projectile_C final : public AProjectileSphere
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0488(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UParticleSystemComponent*               P_Mod_ExplosiveShot_Projectile;                    // 0x0490(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Mesh_Sphere_Warped_02;                             // 0x0498(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URotatorComponent*                      Rotator;                                           // 0x04A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Mod_ExplosiveShot_Projectile(int32 EntryPoint);
	void OnProjectileHit(const struct FHitResult& Hit);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Mod_ExplosiveShot_Projectile_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Mod_ExplosiveShot_Projectile_C")
	}
	static class AMod_ExplosiveShot_Projectile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMod_ExplosiveShot_Projectile_C>();
	}
};
DUMPER7_ASSERTS_AMod_ExplosiveShot_Projectile_C;

}

