#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Mod_WildfireShot

#include "Basic.hpp"

#include "Mod_WildfireShot_classes.hpp"
#include "Mod_WildfireShot_parameters.hpp"


namespace SDK
{

// Function Mod_WildfireShot.Mod_WildfireShot_C.ExecuteUbergraph_Mod_WildfireShot
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMod_WildfireShot_C::ExecuteUbergraph_Mod_WildfireShot(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mod_WildfireShot_C", "ExecuteUbergraph_Mod_WildfireShot");

	Params::Mod_WildfireShot_C_ExecuteUbergraph_Mod_WildfireShot Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Mod_WildfireShot.Mod_WildfireShot_C.OnFire
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FVector&                   from                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   to                                                     (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   WeaponSpread                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMod_WildfireShot_C::OnFire(const struct FVector& from, const struct FVector& to, float WeaponSpread)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mod_WildfireShot_C", "OnFire");

	Params::Mod_WildfireShot_C_OnFire Parms{};

	Parms.from = std::move(from);
	Parms.to = std::move(to);
	Parms.WeaponSpread = WeaponSpread;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Mod_WildfireShot.Mod_WildfireShot_C.ModifyInspectInfo
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UItemInstanceData*                InInstanceData                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FInspectInfo&                    Info                                                   (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool*                                   Rtn                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AMod_WildfireShot_C::ModifyInspectInfo(class AActor* Actor, class UItemInstanceData* InInstanceData, struct FInspectInfo& Info, bool* Rtn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mod_WildfireShot_C", "ModifyInspectInfo");

	Params::Mod_WildfireShot_C_ModifyInspectInfo Parms{};

	Parms.Actor = Actor;
	Parms.InInstanceData = InInstanceData;
	Parms.Info = std::move(Info);

	UObject::ProcessEvent(Func, &Parms);

	Info = std::move(Parms.Info);

	if (Rtn != nullptr)
		*Rtn = Parms.Rtn;
}


// Function Mod_WildfireShot.Mod_WildfireShot_C.ModifyDamage
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FDamageInfo&                     Info                                                   (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// bool*                                   Rtn                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AMod_WildfireShot_C::ModifyDamage(struct FDamageInfo& Info, bool* Rtn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mod_WildfireShot_C", "ModifyDamage");

	Params::Mod_WildfireShot_C_ModifyDamage Parms{};

	Parms.Info = std::move(Info);

	UObject::ProcessEvent(Func, &Parms);

	Info = std::move(Parms.Info);

	if (Rtn != nullptr)
		*Rtn = Parms.Rtn;
}


// Function Mod_WildfireShot.Mod_WildfireShot_C.GetDoTDamage
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float*                                  Out                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMod_WildfireShot_C::GetDoTDamage(float* Out)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mod_WildfireShot_C", "GetDoTDamage");

	Params::Mod_WildfireShot_C_GetDoTDamage Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Out != nullptr)
		*Out = Parms.Out;
}


// Function Mod_WildfireShot.Mod_WildfireShot_C.GetDotDuration
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float*                                  Out                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMod_WildfireShot_C::GetDotDuration(float* Out)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Mod_WildfireShot_C", "GetDotDuration");

	Params::Mod_WildfireShot_C_GetDotDuration Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Out != nullptr)
		*Out = Parms.Out;
}

}

