#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Quest_SmallD_RootCultist

#include "Basic.hpp"

#include "Quest_SmallD_RootCultist_classes.hpp"
#include "Quest_SmallD_RootCultist_parameters.hpp"


namespace SDK
{

// Function Quest_SmallD_RootCultist.Quest_SmallD_RootCultist_C.MakeCultistHostile
// (BlueprintCallable, BlueprintEvent)

void AQuest_SmallD_RootCultist_C::MakeCultistHostile()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Quest_SmallD_RootCultist_C", "MakeCultistHostile");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Quest_SmallD_RootCultist.Quest_SmallD_RootCultist_C.GiveOptionalReward
// (BlueprintCallable, BlueprintEvent)

void AQuest_SmallD_RootCultist_C::GiveOptionalReward()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Quest_SmallD_RootCultist_C", "GiveOptionalReward");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Quest_SmallD_RootCultist.Quest_SmallD_RootCultist_C.BndEvt__Nexus2_K2Node_ComponentBoundEvent_3_QuestActorDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AQuest_SmallD_RootCultist_C::BndEvt__Nexus2_K2Node_ComponentBoundEvent_3_QuestActorDelegate__DelegateSignature(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Quest_SmallD_RootCultist_C", "BndEvt__Nexus2_K2Node_ComponentBoundEvent_3_QuestActorDelegate__DelegateSignature");

	Params::Quest_SmallD_RootCultist_C_BndEvt__Nexus2_K2Node_ComponentBoundEvent_3_QuestActorDelegate__DelegateSignature Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Quest_SmallD_RootCultist.Quest_SmallD_RootCultist_C.BndEvt__Nexus1_K2Node_ComponentBoundEvent_0_QuestActorDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AQuest_SmallD_RootCultist_C::BndEvt__Nexus1_K2Node_ComponentBoundEvent_0_QuestActorDelegate__DelegateSignature(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Quest_SmallD_RootCultist_C", "BndEvt__Nexus1_K2Node_ComponentBoundEvent_0_QuestActorDelegate__DelegateSignature");

	Params::Quest_SmallD_RootCultist_C_BndEvt__Nexus1_K2Node_ComponentBoundEvent_0_QuestActorDelegate__DelegateSignature Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Quest_SmallD_RootCultist.Quest_SmallD_RootCultist_C.BndEvt__KillNexus2_K2Node_ComponentBoundEvent_3_QuestVoidDelegate__DelegateSignature
// (BlueprintEvent)

void AQuest_SmallD_RootCultist_C::BndEvt__KillNexus2_K2Node_ComponentBoundEvent_3_QuestVoidDelegate__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Quest_SmallD_RootCultist_C", "BndEvt__KillNexus2_K2Node_ComponentBoundEvent_3_QuestVoidDelegate__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Quest_SmallD_RootCultist.Quest_SmallD_RootCultist_C.BndEvt__KillNexus1_K2Node_ComponentBoundEvent_2_QuestVoidDelegate__DelegateSignature
// (BlueprintEvent)

void AQuest_SmallD_RootCultist_C::BndEvt__KillNexus1_K2Node_ComponentBoundEvent_2_QuestVoidDelegate__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Quest_SmallD_RootCultist_C", "BndEvt__KillNexus1_K2Node_ComponentBoundEvent_2_QuestVoidDelegate__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Quest_SmallD_RootCultist.Quest_SmallD_RootCultist_C.BndEvt__Kill_Cultist_K2Node_ComponentBoundEvent_9_QuestVoidDelegate__DelegateSignature
// (BlueprintEvent)

void AQuest_SmallD_RootCultist_C::BndEvt__Kill_Cultist_K2Node_ComponentBoundEvent_9_QuestVoidDelegate__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Quest_SmallD_RootCultist_C", "BndEvt__Kill_Cultist_K2Node_ComponentBoundEvent_9_QuestVoidDelegate__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Quest_SmallD_RootCultist.Quest_SmallD_RootCultist_C.BndEvt__Cultist_K2Node_ComponentBoundEvent_6_QuestActorDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AQuest_SmallD_RootCultist_C::BndEvt__Cultist_K2Node_ComponentBoundEvent_6_QuestActorDelegate__DelegateSignature(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Quest_SmallD_RootCultist_C", "BndEvt__Cultist_K2Node_ComponentBoundEvent_6_QuestActorDelegate__DelegateSignature");

	Params::Quest_SmallD_RootCultist_C_BndEvt__Cultist_K2Node_ComponentBoundEvent_6_QuestActorDelegate__DelegateSignature Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Quest_SmallD_RootCultist.Quest_SmallD_RootCultist_C.ExecuteUbergraph_Quest_SmallD_RootCultist
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AQuest_SmallD_RootCultist_C::ExecuteUbergraph_Quest_SmallD_RootCultist(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Quest_SmallD_RootCultist_C", "ExecuteUbergraph_Quest_SmallD_RootCultist");

	Params::Quest_SmallD_RootCultist_C_ExecuteUbergraph_Quest_SmallD_RootCultist Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

