#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Quest_Boss_TheHarrow_Dungeon

#include "Basic.hpp"

#include "Quest_Dungeon_POILink_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Quest_Boss_TheHarrow_Dungeon.Quest_Boss_TheHarrow_Dungeon_C
// 0x0000 (0x05B0 - 0x05B0)
class AQuest_Boss_TheHarrow_Dungeon_C final : public AQuest_Dungeon_POILink_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Quest_Boss_TheHarrow_Dungeon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Quest_Boss_TheHarrow_Dungeon_C")
	}
	static class AQuest_Boss_TheHarrow_Dungeon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AQuest_Boss_TheHarrow_Dungeon_C>();
	}
};
DUMPER7_ASSERTS_AQuest_Boss_TheHarrow_Dungeon_C;

}

