#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Quest_SunGate

#include "Basic.hpp"

#include "Quest_SunGate_classes.hpp"
#include "Quest_SunGate_parameters.hpp"


namespace SDK
{

// Function Quest_SunGate.Quest_SunGate_C.OnHowlingKeyUsed
// (BlueprintCallable, BlueprintEvent)

void AQuest_SunGate_C::OnHowlingKeyUsed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Quest_SunGate_C", "OnHowlingKeyUsed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Quest_SunGate.Quest_SunGate_C.GiveTrait
// (BlueprintCallable, BlueprintEvent)

void AQuest_SunGate_C::GiveTrait()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Quest_SunGate_C", "GiveTrait");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Quest_SunGate.Quest_SunGate_C.BndEvt__ZoneToKing_K2Node_ComponentBoundEvent_0_QuestActorDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AQuest_SunGate_C::BndEvt__ZoneToKing_K2Node_ComponentBoundEvent_0_QuestActorDelegate__DelegateSignature(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Quest_SunGate_C", "BndEvt__ZoneToKing_K2Node_ComponentBoundEvent_0_QuestActorDelegate__DelegateSignature");

	Params::Quest_SunGate_C_BndEvt__ZoneToKing_K2Node_ComponentBoundEvent_0_QuestActorDelegate__DelegateSignature Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Quest_SunGate.Quest_SunGate_C.ExecuteUbergraph_Quest_SunGate
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AQuest_SunGate_C::ExecuteUbergraph_Quest_SunGate(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Quest_SunGate_C", "ExecuteUbergraph_Quest_SunGate");

	Params::Quest_SunGate_C_ExecuteUbergraph_Quest_SunGate Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

