#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Quest_SmallD_LastWill

#include "Basic.hpp"

#include "Quest_SmallD_LastWill_classes.hpp"
#include "Quest_SmallD_LastWill_parameters.hpp"


namespace SDK
{

// Function Quest_SmallD_LastWill.Quest_SmallD_LastWill_C.PickedUpKey
// (BlueprintCallable, BlueprintEvent)

void AQuest_SmallD_LastWill_C::PickedUpKey()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Quest_SmallD_LastWill_C", "PickedUpKey");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Quest_SmallD_LastWill.Quest_SmallD_LastWill_C.BndEvt__MonkeyDoor_K2Node_ComponentBoundEvent_1_QuestActorDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AQuest_SmallD_LastWill_C::BndEvt__MonkeyDoor_K2Node_ComponentBoundEvent_1_QuestActorDelegate__DelegateSignature(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Quest_SmallD_LastWill_C", "BndEvt__MonkeyDoor_K2Node_ComponentBoundEvent_1_QuestActorDelegate__DelegateSignature");

	Params::Quest_SmallD_LastWill_C_BndEvt__MonkeyDoor_K2Node_ComponentBoundEvent_1_QuestActorDelegate__DelegateSignature Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Quest_SmallD_LastWill.Quest_SmallD_LastWill_C.BndEvt__Loot_K2Node_ComponentBoundEvent_2_QuestActorDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AQuest_SmallD_LastWill_C::BndEvt__Loot_K2Node_ComponentBoundEvent_2_QuestActorDelegate__DelegateSignature(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Quest_SmallD_LastWill_C", "BndEvt__Loot_K2Node_ComponentBoundEvent_2_QuestActorDelegate__DelegateSignature");

	Params::Quest_SmallD_LastWill_C_BndEvt__Loot_K2Node_ComponentBoundEvent_2_QuestActorDelegate__DelegateSignature Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Quest_SmallD_LastWill.Quest_SmallD_LastWill_C.Activate Find the Key
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FName&                      StateName                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Other                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AQuest_SmallD_LastWill_C::Activate_Find_the_Key(const class FName& StateName, class AActor* Other)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Quest_SmallD_LastWill_C", "Activate Find the Key");

	Params::Quest_SmallD_LastWill_C_Activate_Find_the_Key Parms{};

	Parms.StateName = StateName;
	Parms.Other = Other;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Quest_SmallD_LastWill.Quest_SmallD_LastWill_C.ExecuteUbergraph_Quest_SmallD_LastWill
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AQuest_SmallD_LastWill_C::ExecuteUbergraph_Quest_SmallD_LastWill(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Quest_SmallD_LastWill_C", "ExecuteUbergraph_Quest_SmallD_LastWill");

	Params::Quest_SmallD_LastWill_C_ExecuteUbergraph_Quest_SmallD_LastWill Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

