#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SpawnPoint_NPC

#include "Basic.hpp"


namespace SDK::Params
{

// Function SpawnPoint_NPC.SpawnPoint_NPC_C.UserConstructionScript
// 0x0038 (0x0038 - 0x0000)
struct SpawnPoint_NPC_C_UserConstructionScript final
{
public:
	class FText                                   CallFunc_MakeLiteralText_ReturnValue;              // 0x0000(0x0018)()
	class FText                                   CallFunc_MakeLiteralText_ReturnValue1;             // 0x0018(0x0018)()
	bool                                          CallFunc_EqualEqual_TextText_ReturnValue;          // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_SpawnPoint_NPC_C_UserConstructionScript;

}

