#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Trinket_RingOfTheAdmiral

#include "Basic.hpp"

#include "Trinket_RingOfTheAdmiral_classes.hpp"
#include "Trinket_RingOfTheAdmiral_parameters.hpp"


namespace SDK
{

// Function Trinket_RingOfTheAdmiral.Trinket_RingOfTheAdmiral_C.ExecuteUbergraph_Trinket_RingOfTheAdmiral
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATrinket_RingOfTheAdmiral_C::ExecuteUbergraph_Trinket_RingOfTheAdmiral(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Trinket_RingOfTheAdmiral_C", "ExecuteUbergraph_Trinket_RingOfTheAdmiral");

	Params::Trinket_RingOfTheAdmiral_C_ExecuteUbergraph_Trinket_RingOfTheAdmiral Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Trinket_RingOfTheAdmiral.Trinket_RingOfTheAdmiral_C.OnComputeStats
// (Event, Protected, BlueprintEvent)

void ATrinket_RingOfTheAdmiral_C::OnComputeStats()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Trinket_RingOfTheAdmiral_C", "OnComputeStats");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Trinket_RingOfTheAdmiral.Trinket_RingOfTheAdmiral_C.ModifyInspectInfo
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UItemInstanceData*                InInstanceData                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FInspectInfo&                    Info                                                   (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool*                                   Rtn                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ATrinket_RingOfTheAdmiral_C::ModifyInspectInfo(class AActor* Actor, class UItemInstanceData* InInstanceData, struct FInspectInfo& Info, bool* Rtn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Trinket_RingOfTheAdmiral_C", "ModifyInspectInfo");

	Params::Trinket_RingOfTheAdmiral_C_ModifyInspectInfo Parms{};

	Parms.Actor = Actor;
	Parms.InInstanceData = InInstanceData;
	Parms.Info = std::move(Info);

	UObject::ProcessEvent(Func, &Parms);

	Info = std::move(Parms.Info);

	if (Rtn != nullptr)
		*Rtn = Parms.Rtn;
}

}

