#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_BuySellConfirm

#include "Basic.hpp"

#include "Widget_BuySellConfirm_classes.hpp"
#include "Widget_BuySellConfirm_parameters.hpp"


namespace SDK
{

// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.ExecuteUbergraph_Widget_BuySellConfirm
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_BuySellConfirm_C::ExecuteUbergraph_Widget_BuySellConfirm(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "ExecuteUbergraph_Widget_BuySellConfirm");

	Params::Widget_BuySellConfirm_C_ExecuteUbergraph_Widget_BuySellConfirm Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWidget_BuySellConfirm_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.BndEvt__Widget_ButtonEx_C_0_K2Node_ComponentBoundEvent_1017_OnAdvButtonClickedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWidget*                          Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_BuySellConfirm_C::BndEvt__Widget_ButtonEx_C_0_K2Node_ComponentBoundEvent_1017_OnAdvButtonClickedEvent__DelegateSignature(class UWidget* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "BndEvt__Widget_ButtonEx_C_0_K2Node_ComponentBoundEvent_1017_OnAdvButtonClickedEvent__DelegateSignature");

	Params::Widget_BuySellConfirm_C_BndEvt__Widget_ButtonEx_C_0_K2Node_ComponentBoundEvent_1017_OnAdvButtonClickedEvent__DelegateSignature Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.BndEvt__FocusButtonWidget_134_K2Node_ComponentBoundEvent_634_OnAdvButtonClickedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWidget*                          Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_BuySellConfirm_C::BndEvt__FocusButtonWidget_134_K2Node_ComponentBoundEvent_634_OnAdvButtonClickedEvent__DelegateSignature(class UWidget* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "BndEvt__FocusButtonWidget_134_K2Node_ComponentBoundEvent_634_OnAdvButtonClickedEvent__DelegateSignature");

	Params::Widget_BuySellConfirm_C_BndEvt__FocusButtonWidget_134_K2Node_ComponentBoundEvent_634_OnAdvButtonClickedEvent__DelegateSignature Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.BndEvt__FocusButtonWidget_90_K2Node_ComponentBoundEvent_484_OnAdvButtonClickedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWidget*                          Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_BuySellConfirm_C::BndEvt__FocusButtonWidget_90_K2Node_ComponentBoundEvent_484_OnAdvButtonClickedEvent__DelegateSignature(class UWidget* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "BndEvt__FocusButtonWidget_90_K2Node_ComponentBoundEvent_484_OnAdvButtonClickedEvent__DelegateSignature");

	Params::Widget_BuySellConfirm_C_BndEvt__FocusButtonWidget_90_K2Node_ComponentBoundEvent_484_OnAdvButtonClickedEvent__DelegateSignature Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.BndEvt__No_K2Node_ComponentBoundEvent_240_OnAdvButtonClickedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWidget*                          Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_BuySellConfirm_C::BndEvt__No_K2Node_ComponentBoundEvent_240_OnAdvButtonClickedEvent__DelegateSignature(class UWidget* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "BndEvt__No_K2Node_ComponentBoundEvent_240_OnAdvButtonClickedEvent__DelegateSignature");

	Params::Widget_BuySellConfirm_C_BndEvt__No_K2Node_ComponentBoundEvent_240_OnAdvButtonClickedEvent__DelegateSignature Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.BndEvt__Yes_K2Node_ComponentBoundEvent_154_OnAdvButtonClickedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWidget*                          Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_BuySellConfirm_C::BndEvt__Yes_K2Node_ComponentBoundEvent_154_OnAdvButtonClickedEvent__DelegateSignature(class UWidget* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "BndEvt__Yes_K2Node_ComponentBoundEvent_154_OnAdvButtonClickedEvent__DelegateSignature");

	Params::Widget_BuySellConfirm_C_BndEvt__Yes_K2Node_ComponentBoundEvent_154_OnAdvButtonClickedEvent__DelegateSignature Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.GetInventoryItem
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Out                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWidget_BuySellConfirm_C::GetInventoryItem(bool* Out)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "GetInventoryItem");

	Params::Widget_BuySellConfirm_C_GetInventoryItem Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Out != nullptr)
		*Out = Parms.Out;
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.Init
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Sell_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   ItemID_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_BuySellConfirm_C::Init(bool Sell_0, int32 ItemID_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "Init");

	Params::Widget_BuySellConfirm_C_Init Parms{};

	Parms.Sell_0 = Sell_0;
	Parms.ItemID_0 = ItemID_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.Get_Icon_Brush_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UWidget_BuySellConfirm_C::Get_Icon_Brush_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "Get_Icon_Brush_0");

	Params::Widget_BuySellConfirm_C_Get_Icon_Brush_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.Get_Label_Text_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWidget_BuySellConfirm_C::Get_Label_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "Get_Label_Text_0");

	Params::Widget_BuySellConfirm_C_Get_Label_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.Get_QuantityLabel_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWidget_BuySellConfirm_C::Get_QuantityLabel_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "Get_QuantityLabel_Text_0");

	Params::Widget_BuySellConfirm_C_Get_QuantityLabel_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.Get_QuantityAvailable_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWidget_BuySellConfirm_C::Get_QuantityAvailable_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "Get_QuantityAvailable_Text_0");

	Params::Widget_BuySellConfirm_C_Get_QuantityAvailable_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.Get_Cost_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWidget_BuySellConfirm_C::Get_Cost_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "Get_Cost_Text_0");

	Params::Widget_BuySellConfirm_C_Get_Cost_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.CanAfford
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Quantity_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Out                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWidget_BuySellConfirm_C::CanAfford(int32 Quantity_0, bool* Out)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "CanAfford");

	Params::Widget_BuySellConfirm_C_CanAfford Parms{};

	Parms.Quantity_0 = Quantity_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Out != nullptr)
		*Out = Parms.Out;
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.GetCost
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   Quantity_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  Cost_0                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_BuySellConfirm_C::GetCost(int32 Quantity_0, int32* Cost_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "GetCost");

	Params::Widget_BuySellConfirm_C_GetCost Parms{};

	Parms.Quantity_0 = Quantity_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Cost_0 != nullptr)
		*Cost_0 = Parms.Cost_0;
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.Get_Yes_bIsEnabled_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWidget_BuySellConfirm_C::Get_Yes_bIsEnabled_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "Get_Yes_bIsEnabled_0");

	Params::Widget_BuySellConfirm_C_Get_Yes_bIsEnabled_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.Get_QuantityLabel_ColorAndOpacity_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateColor                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateColor UWidget_BuySellConfirm_C::Get_QuantityLabel_ColorAndOpacity_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "Get_QuantityLabel_ColorAndOpacity_0");

	Params::Widget_BuySellConfirm_C_Get_QuantityLabel_ColorAndOpacity_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.Get_Cost_ColorAndOpacity_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateColor                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateColor UWidget_BuySellConfirm_C::Get_Cost_ColorAndOpacity_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "Get_Cost_ColorAndOpacity_0");

	Params::Widget_BuySellConfirm_C_Get_Cost_ColorAndOpacity_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.Get_Title_Text_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWidget_BuySellConfirm_C::Get_Title_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "Get_Title_Text_0");

	Params::Widget_BuySellConfirm_C_Get_Title_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.Get_Cost_Visibility_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWidget_BuySellConfirm_C::Get_Cost_Visibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "Get_Cost_Visibility_0");

	Params::Widget_BuySellConfirm_C_Get_Cost_Visibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.Get_QuantityLabel_Visibility_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWidget_BuySellConfirm_C::Get_QuantityLabel_Visibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "Get_QuantityLabel_Visibility_0");

	Params::Widget_BuySellConfirm_C_Get_QuantityLabel_Visibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.GetQuantity
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32*                                  Out                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_BuySellConfirm_C::GetQuantity(int32* Out)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "GetQuantity");

	Params::Widget_BuySellConfirm_C_GetQuantity Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Out != nullptr)
		*Out = Parms.Out;
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.BuyItem
// (Public, BlueprintCallable, BlueprintEvent)

void UWidget_BuySellConfirm_C::BuyItem()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "BuyItem");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.SellItem
// (Public, BlueprintCallable, BlueprintEvent)

void UWidget_BuySellConfirm_C::SellItem()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "SellItem");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.HasScrap
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   Scrap                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Cost_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Out                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWidget_BuySellConfirm_C::HasScrap(int32 Scrap, int32 Cost_0, bool* Out)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "HasScrap");

	Params::Widget_BuySellConfirm_C_HasScrap Parms{};

	Parms.Scrap = Scrap;
	Parms.Cost_0 = Cost_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Out != nullptr)
		*Out = Parms.Out;
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.GetScrap
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UInventoryComponent*              InventoryComponent                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  Scrap                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_BuySellConfirm_C::GetScrap(class UInventoryComponent* InventoryComponent, int32* Scrap)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "GetScrap");

	Params::Widget_BuySellConfirm_C_GetScrap Parms{};

	Parms.InventoryComponent = InventoryComponent;

	UObject::ProcessEvent(Func, &Parms);

	if (Scrap != nullptr)
		*Scrap = Parms.Scrap;
}


// Function Widget_BuySellConfirm.Widget_BuySellConfirm_C.GetMaxBuyQuantity
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32*                                  Out                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_BuySellConfirm_C::GetMaxBuyQuantity(int32* Out)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_BuySellConfirm_C", "GetMaxBuyQuantity");

	Params::Widget_BuySellConfirm_C_GetMaxBuyQuantity Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Out != nullptr)
		*Out = Parms.Out;
}

}

