#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_MiniMap_Objective

#include "Basic.hpp"

#include "Widget_MiniMap_Objective_classes.hpp"
#include "Widget_MiniMap_Objective_parameters.hpp"


namespace SDK
{

// Function Widget_MiniMap_Objective.Widget_MiniMap_Objective_C.UpdateMiniMapWidget
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FWidgetTransform&          InTransform                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
// struct FWidgetTransform                 ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor)

struct FWidgetTransform UWidget_MiniMap_Objective_C::UpdateMiniMapWidget(const struct FWidgetTransform& InTransform)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_MiniMap_Objective_C", "UpdateMiniMapWidget");

	Params::Widget_MiniMap_Objective_C_UpdateMiniMapWidget Parms{};

	Parms.InTransform = std::move(InTransform);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Widget_MiniMap_Objective.Widget_MiniMap_Objective_C.OnRegisteredToPanel
// (Event, Public, BlueprintEvent)
// Parameters:
// class UMiniMapPanel*                    MiniMapPanel                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_MiniMap_Objective_C::OnRegisteredToPanel(class UMiniMapPanel* MiniMapPanel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_MiniMap_Objective_C", "OnRegisteredToPanel");

	Params::Widget_MiniMap_Objective_C_OnRegisteredToPanel Parms{};

	Parms.MiniMapPanel = MiniMapPanel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_MiniMap_Objective.Widget_MiniMap_Objective_C.OnDead_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   Reason                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ACharacterGunfire*                Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Cause                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_MiniMap_Objective_C::OnDead_Event_0(uint8 Reason, class ACharacterGunfire* Character, class AActor* Cause)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_MiniMap_Objective_C", "OnDead_Event_0");

	Params::Widget_MiniMap_Objective_C_OnDead_Event_0 Parms{};

	Parms.Reason = Reason;
	Parms.Character = Character;
	Parms.Cause = Cause;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_MiniMap_Objective.Widget_MiniMap_Objective_C.ExecuteUbergraph_Widget_MiniMap_Objective
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_MiniMap_Objective_C::ExecuteUbergraph_Widget_MiniMap_Objective(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_MiniMap_Objective_C", "ExecuteUbergraph_Widget_MiniMap_Objective");

	Params::Widget_MiniMap_Objective_C_ExecuteUbergraph_Widget_MiniMap_Objective Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

