#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_Screen_Option

#include "Basic.hpp"

#include "GunfireRuntime_structs.hpp"


namespace SDK::Params
{

// Function Widget_Screen_Option.Widget_Screen_Option_C.On Option Selected
// 0x0020 (0x0020 - 0x0000)
struct Widget_Screen_Option_C_On_Option_Selected final
{
public:
	class APlayerController*                      CallFunc_Get_Inspector_Player_Controller;          // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ARemnant_PlayerController_C*            K2Node_DynamicCast_AsRemnant_Player_Controller;    // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_12[0x6];                                       // 0x0012(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_Screen_Option_C_On_Option_Selected;

// Function Widget_Screen_Option.Widget_Screen_Option_C.Set Option Value
// 0x0048 (0x0048 - 0x0000)
struct Widget_Screen_Option_C_Set_Option_Value final
{
public:
	class UWidget_Screen_C*                       Screen;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FDialogOption                          Option_0;                                          // 0x0008(0x0040)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_Widget_Screen_Option_C_Set_Option_Value;

}

