#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_CheckpointOption

#include "Basic.hpp"

#include "Widget_CheckpointOption_classes.hpp"
#include "Widget_CheckpointOption_parameters.hpp"


namespace SDK
{

// Function Widget_CheckpointOption.Widget_CheckpointOption_C.ExecuteUbergraph_Widget_CheckpointOption
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_CheckpointOption_C::ExecuteUbergraph_Widget_CheckpointOption(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CheckpointOption_C", "ExecuteUbergraph_Widget_CheckpointOption");

	Params::Widget_CheckpointOption_C_ExecuteUbergraph_Widget_CheckpointOption Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_CheckpointOption.Widget_CheckpointOption_C.SimulateClick
// (BlueprintCallable, BlueprintEvent)

void UWidget_CheckpointOption_C::SimulateClick()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CheckpointOption_C", "SimulateClick");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Widget_CheckpointOption.Widget_CheckpointOption_C.BndEvt__FocusButton_K2Node_ComponentBoundEvent_2_OnAdvButtonClickedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWidget*                          Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_CheckpointOption_C::BndEvt__FocusButton_K2Node_ComponentBoundEvent_2_OnAdvButtonClickedEvent__DelegateSignature(class UWidget* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CheckpointOption_C", "BndEvt__FocusButton_K2Node_ComponentBoundEvent_2_OnAdvButtonClickedEvent__DelegateSignature");

	Params::Widget_CheckpointOption_C_BndEvt__FocusButton_K2Node_ComponentBoundEvent_2_OnAdvButtonClickedEvent__DelegateSignature Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_CheckpointOption.Widget_CheckpointOption_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWidget_CheckpointOption_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CheckpointOption_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Widget_CheckpointOption.Widget_CheckpointOption_C.BndEvt__FocusButton_K2Node_ComponentBoundEvent_1315_OnAdvButtonClickedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWidget*                          Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_CheckpointOption_C::BndEvt__FocusButton_K2Node_ComponentBoundEvent_1315_OnAdvButtonClickedEvent__DelegateSignature(class UWidget* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CheckpointOption_C", "BndEvt__FocusButton_K2Node_ComponentBoundEvent_1315_OnAdvButtonClickedEvent__DelegateSignature");

	Params::Widget_CheckpointOption_C_BndEvt__FocusButton_K2Node_ComponentBoundEvent_1315_OnAdvButtonClickedEvent__DelegateSignature Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_CheckpointOption.Widget_CheckpointOption_C.BndEvt__FocusButton_K2Node_ComponentBoundEvent_1278_OnAdvButtonClickedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWidget*                          Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_CheckpointOption_C::BndEvt__FocusButton_K2Node_ComponentBoundEvent_1278_OnAdvButtonClickedEvent__DelegateSignature(class UWidget* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CheckpointOption_C", "BndEvt__FocusButton_K2Node_ComponentBoundEvent_1278_OnAdvButtonClickedEvent__DelegateSignature");

	Params::Widget_CheckpointOption_C_BndEvt__FocusButton_K2Node_ComponentBoundEvent_1278_OnAdvButtonClickedEvent__DelegateSignature Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_CheckpointOption.Widget_CheckpointOption_C.DoAction
// (Public, BlueprintCallable, BlueprintEvent)

void UWidget_CheckpointOption_C::DoAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CheckpointOption_C", "DoAction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Widget_CheckpointOption.Widget_CheckpointOption_C.ActivateCheckpoint
// (Public, BlueprintCallable, BlueprintEvent)

void UWidget_CheckpointOption_C::ActivateCheckpoint()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CheckpointOption_C", "ActivateCheckpoint");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Widget_CheckpointOption.Widget_CheckpointOption_C.IsFocusedVisibility
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWidget_CheckpointOption_C::IsFocusedVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CheckpointOption_C", "IsFocusedVisibility");

	Params::Widget_CheckpointOption_C_IsFocusedVisibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Widget_CheckpointOption.Widget_CheckpointOption_C.OpenTravelMenuDialog
// (Public, BlueprintCallable, BlueprintEvent)

void UWidget_CheckpointOption_C::OpenTravelMenuDialog()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CheckpointOption_C", "OpenTravelMenuDialog");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Widget_CheckpointOption.Widget_CheckpointOption_C.IsValid
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   Out                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWidget_CheckpointOption_C::IsValid(bool* Out)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CheckpointOption_C", "IsValid");

	Params::Widget_CheckpointOption_C_IsValid Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Out != nullptr)
		*Out = Parms.Out;
}


// Function Widget_CheckpointOption.Widget_CheckpointOption_C.OpenWorldSettingsDialog
// (Public, BlueprintCallable, BlueprintEvent)

void UWidget_CheckpointOption_C::OpenWorldSettingsDialog()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CheckpointOption_C", "OpenWorldSettingsDialog");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Widget_CheckpointOption.Widget_CheckpointOption_C.SurvivalMode
// (Public, BlueprintCallable, BlueprintEvent)

void UWidget_CheckpointOption_C::SurvivalMode()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_CheckpointOption_C", "SurvivalMode");

	UObject::ProcessEvent(Func, nullptr);
}

}

