#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_FocusWidget

#include "Basic.hpp"

#include "Widget_FocusWidget_classes.hpp"
#include "Widget_FocusWidget_parameters.hpp"


namespace SDK
{

// Function Widget_FocusWidget.Widget_FocusWidget_C.GetContextActor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class AActor**                          Actor                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_FocusWidget_C::GetContextActor(class AActor** Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_FocusWidget_C", "GetContextActor");

	Params::Widget_FocusWidget_C_GetContextActor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Actor != nullptr)
		*Actor = Parms.Actor;
}


// Function Widget_FocusWidget.Widget_FocusWidget_C.GetInventory
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UInventoryComponent**             Inventory                                              (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_FocusWidget_C::GetInventory(class UInventoryComponent** Inventory)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_FocusWidget_C", "GetInventory");

	Params::Widget_FocusWidget_C_GetInventory Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Inventory != nullptr)
		*Inventory = Parms.Inventory;
}


// Function Widget_FocusWidget.Widget_FocusWidget_C.GetCrafting
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UCraftingComponent**              Crafting                                               (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_FocusWidget_C::GetCrafting(class UCraftingComponent** Crafting)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_FocusWidget_C", "GetCrafting");

	Params::Widget_FocusWidget_C_GetCrafting Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Crafting != nullptr)
		*Crafting = Parms.Crafting;
}

}

