#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_Ingredients

#include "Basic.hpp"

#include "Widget_UserWidget_classes.hpp"
#include "GunfireRuntime_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Widget_Ingredients.Widget_Ingredients_C
// 0x0038 (0x0288 - 0x0250)
class UWidget_Ingredients_C final : public UWidget_UserWidget_C
{
public:
	uint8                                         Pad_249[0x7];                                      // 0x0249(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UVerticalBox*                           Ingredients;                                       // 0x0250(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FRecipeInfo                            Recipe;                                            // 0x0258(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	float                                         IngredientSpacing;                                 // 0x0280(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ShowScrap;                                         // 0x0284(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void SetRecipe(const struct FRecipeInfo& Recipe_0);
	void BuildIngredientList();
	void IsScrap(const struct FIngredientInfo& Ingredient, bool* Out);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Widget_Ingredients_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Widget_Ingredients_C")
	}
	static class UWidget_Ingredients_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWidget_Ingredients_C>();
	}
};
DUMPER7_ASSERTS_UWidget_Ingredients_C;

}

