#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Zone_1_0

#include "Basic.hpp"

#include "Zone_1_0_classes.hpp"
#include "Zone_1_0_parameters.hpp"


namespace SDK
{

// Function Zone_1_0.PlayerBase01_C.ExecuteUbergraph_PlayerBase01
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APlayerBase01_C::ExecuteUbergraph_PlayerBase01(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerBase01_C", "ExecuteUbergraph_PlayerBase01");

	Params::PlayerBase01_C_ExecuteUbergraph_PlayerBase01 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Zone_1_0.PlayerBase01_C.InpActEvt_Shift_Nine_K2Node_InputKeyEvent_0
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APlayerBase01_C::InpActEvt_Shift_Nine_K2Node_InputKeyEvent_0(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerBase01_C", "InpActEvt_Shift_Nine_K2Node_InputKeyEvent_0");

	Params::PlayerBase01_C_InpActEvt_Shift_Nine_K2Node_InputKeyEvent_0 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Zone_1_0.PlayerBase01_C.InpActEvt_Shift_Eight_K2Node_InputKeyEvent_1
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APlayerBase01_C::InpActEvt_Shift_Eight_K2Node_InputKeyEvent_1(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerBase01_C", "InpActEvt_Shift_Eight_K2Node_InputKeyEvent_1");

	Params::PlayerBase01_C_InpActEvt_Shift_Eight_K2Node_InputKeyEvent_1 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Zone_1_0.PlayerBase01_C.InpActEvt_Shift_Seven_K2Node_InputKeyEvent_2
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APlayerBase01_C::InpActEvt_Shift_Seven_K2Node_InputKeyEvent_2(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerBase01_C", "InpActEvt_Shift_Seven_K2Node_InputKeyEvent_2");

	Params::PlayerBase01_C_InpActEvt_Shift_Seven_K2Node_InputKeyEvent_2 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Zone_1_0.PlayerBase01_C.InpActEvt_Shift_Six_K2Node_InputKeyEvent_3
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APlayerBase01_C::InpActEvt_Shift_Six_K2Node_InputKeyEvent_3(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerBase01_C", "InpActEvt_Shift_Six_K2Node_InputKeyEvent_3");

	Params::PlayerBase01_C_InpActEvt_Shift_Six_K2Node_InputKeyEvent_3 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Zone_1_0.PlayerBase01_C.InpActEvt_Shift_Three_K2Node_InputKeyEvent_4
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APlayerBase01_C::InpActEvt_Shift_Three_K2Node_InputKeyEvent_4(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerBase01_C", "InpActEvt_Shift_Three_K2Node_InputKeyEvent_4");

	Params::PlayerBase01_C_InpActEvt_Shift_Three_K2Node_InputKeyEvent_4 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Zone_1_0.PlayerBase01_C.InpActEvt_Shift_Five_K2Node_InputKeyEvent_5
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APlayerBase01_C::InpActEvt_Shift_Five_K2Node_InputKeyEvent_5(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerBase01_C", "InpActEvt_Shift_Five_K2Node_InputKeyEvent_5");

	Params::PlayerBase01_C_InpActEvt_Shift_Five_K2Node_InputKeyEvent_5 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Zone_1_0.PlayerBase01_C.InpActEvt_Shift_Four_K2Node_InputKeyEvent_6
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APlayerBase01_C::InpActEvt_Shift_Four_K2Node_InputKeyEvent_6(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerBase01_C", "InpActEvt_Shift_Four_K2Node_InputKeyEvent_6");

	Params::PlayerBase01_C_InpActEvt_Shift_Four_K2Node_InputKeyEvent_6 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Zone_1_0.PlayerBase01_C.Activate Intro Objective
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             Event                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APlayerBase01_C::Activate_Intro_Objective(class FName Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerBase01_C", "Activate Intro Objective");

	Params::PlayerBase01_C_Activate_Intro_Objective Parms{};

	Parms.Event = Event;

	UObject::ProcessEvent(Func, &Parms);
}

}

