#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ZoneDef_Swamp_Overworld01

#include "Basic.hpp"

#include "Remnant_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ZoneDef_Swamp_Overworld01.ZoneDef_Swamp_Overworld01_C
// 0x0000 (0x0068 - 0x0068)
class UZoneDef_Swamp_Overworld01_C final : public UZoneDef
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ZoneDef_Swamp_Overworld01_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ZoneDef_Swamp_Overworld01_C")
	}
	static class UZoneDef_Swamp_Overworld01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UZoneDef_Swamp_Overworld01_C>();
	}
};
DUMPER7_ASSERTS_UZoneDef_Swamp_Overworld01_C;

}

